---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-sync
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m0s
  path: ./secrets/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
