apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:HQpIWFv551H5DvRykmFoOA+njn5ZIII00RFRBOIuqWiaDAempmIIsVx28QA=,iv:oFi++MamOKg4P1CZfpHW9TnLbVCTy4govcwZZwxnSoA=,tag:zntgClh1M35e04/++TZoeQ==,type:str]
    join.key: ENC[AES256_GCM,data:mn5NM56oulvSgqpKCO262rpr/3j4WPUSjRK3BidTlnvka5MUHgAZYskVnQh2T90CDwfBr1TS749jTDI1CBSbDf+CGSvXxF7JqpWU0vRD86ouqbke/k6EvA==,iv:e+onUOYKVyI2JEeSk/vvlVnlJ5HgS2D3KMpuB4GZsdg=,tag:0B2SuYdMVO7Zw7xAORWhpA==,type:str]
    master.key: ENC[AES256_GCM,data:KUmSdF0GG6ApmtC0md28COh4/4AupfHzE5TzUVB9a34qmK61glWFir3Bpf9Vd+gwCgYrf5SorDh7W4Fzc1Q9W3MeQfdVvuvZ0lBFfNyhbs6R4DCGz/wbww==,iv:KivYOX/A+cpFuiHu3WaY6QUSSdOlJn9KmkQcyhzrLlc=,tag:G9tMDU19Hk8V94tDfzvxpw==,type:str]
    password: ENC[AES256_GCM,data:BwI/fb8MiYNVR8/jTmAAfSHdMImkV0cP/fsXGA==,iv:ALSxsGraIPcZmGSALX3Tln2VxYlTk8zSSFU3jELPC+k=,tag:xkfu1xm1UepI3Dgl56IrsA==,type:str]
    system.yaml: ENC[AES256_GCM,data:kRpzuSgKjdSSCimzwtZ+6kQXvcry2Uy36nl/CCblnNSrUj+8N7zb5KBH6z3LYKVCV1+pI+bMi5n9v4bzN7cNHKbuJPygB7Z06+p2+eBS0oL8aEq0X+YRs9H+CTnhMFNFjv4xZ8c2wXCpsWxos5zbLT6+DonOCiwg1TvkHILb4rBAglZ081B5ZEgCONMw+On2dCZWpTopt52vpMJSW8TXvyqtzXQ6D7+gYvE/FhmT0OV/q6osbwt8IZ102EbMq27lr4FIkrVD9FtJx1PRAvuwvG0Y8JlDhSru/AlSXoMyfNS/wTSeLQps0M7f77SC1soOkF3oWQUCyjoxhjY0g4TIxZdnqIf2f4F2Gfcd26QDmXz8c8UMSqAtJFe0ghFbhhWABUKKE32/Fu/+sKQAEtRMKG2WkX6FiWyl0X+XFwn470eytWrRInOyycofKUHMfX4h1rfk3U7JbscHbXDkwdt2UxtBCp9lri71UZywy9WQ4kxCqt9j/EfCYLO0ZSygjv3LHlmp+3MSztSQyWnX5GA79R7dcwrLS0PEiu6J0VqmnCBcvCiD23DlTKoym8wpii0hB/wJFL3+8yRe1nMD0+yaKOb7Ybm3sMDlg1H9mVs14IoxlJmK8DhsJMUQS8rGH2uTkcWmtQ==,iv:k7d31CLj2DneEBsSp3yJ/9MZSntaeoChcGs+GsCtfRA=,tag:hmTp8/WVSCSwBWLM8BrYBg==,type:str]
    user: ENC[AES256_GCM,data:5rMYgg9F9/NgIMCCLig4Ig==,iv:Xy4P8cRuEAyZJs0frexRp0H27U1MYbOAJCze9iqZY/I=,tag:TVVJG9oeyWhYkCZwBE7oWA==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aVNDcVZ6TFBoRkVwUm1L
            WjN6bzc3ZWpQMkthQU5ST1hHSkhqTDhpUFIwClJzbFJMUDF0bGNvOXl4OVRnT1dK
            TndOcE1CMUNrMlVudnlTNWhKcUEwK1kKLS0tIDdDbkFmTWRLMnd6OFlKWXRWNHJx
            TmZqQzRDck1BVHBhOFJMWnVjZUIwM1UKprCVzRxxzUH8YngB2rj0aJbe8F4r9sOp
            wWu/WC9foYpcHO8cSJhOqlN7bE5zyNB3xJ88CbHtKquchXjskEOM0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T20:10:48Z"
    mac: ENC[AES256_GCM,data:lseK0NPwmoXIlKscsccRWwhLcBuMsdsRvwJSnKwmuvTurMf/WaDjC6yYzRwSCVx+NCQqGlAQyaikie1ZaLDVqlL8N2zEVVd6f1iwO4mt+eNLM8hAIUAxyv7PwVEIio2leVo299qNSKZyk/ekNcs67v5xM+k0h3MTxcBeJyAw1FU=,iv:uCNyd+WHCR1SoMLJzK7+7VUfIBvYa2OywNZoThcKqJc=,tag:6xBNZlKx4xszHUhadnNaNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
