apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:i+ktbLesqUATiL/R0Y76sPXbrqzmZ5pdlJAV8BuhryIEKbdZF9Xg9UXt++M=,iv:cInv0GvtXrbg+G7HGzd696C39IoYjzjxWe/vhyjOKi0=,tag:90oCAbx4nQDEAjNVU+spSw==,type:str]
    join.key: ENC[AES256_GCM,data:VaNwJ/3LZnLsypq+/tXs8rApghC4Ugotcuay666FahL1wpDegBeex9G9WxXFHw7VjNmUAUCUSIWc5Ak+BiaFe2WKN/mk8ARk9d+UleE6+05aOJSviUmFzw==,iv:F2vtJggNWzVfFdH/AedWfEZp86A/ClFed5nGJ+fbe1Q=,tag:nVel+UuPW7wYOB0pz0VY8g==,type:str]
    master.key: ENC[AES256_GCM,data:A7aHVAjTesVnV9vyi9aZ43nLGwQn5bwW5I5u+lnPrwm1GE1Rs/f3gCl0IijGIZJNKMRFcCa8OGTYj+AvBnN97QT6NScTXEgndF/+5IPJOtFM5ZKm+dVXvA==,iv:MV9yUQT52wGsHum1N4ozDFrhMcO+tweK6REtPWDRNRo=,tag:SdnysqBnhPEXfesNFwbMGA==,type:str]
    password: ENC[AES256_GCM,data:5+cAzyrGTAtyemywsNOe7xO6sPo3wlO000mQsA==,iv:7DijWjEbc/Y2dAr7If15TMxDqSRtRRZvtwwcq8LXYsI=,tag:GivoWMFBrX25xnRB7whiUA==,type:str]
    system.yaml: ENC[AES256_GCM,data:LNfdlCkMlSuZi9bVyaZb3EnT8o3aJ2a1yQGqAyqolgT6UTEOylN8orEtdQ8i0R7j3HfdQvO7oV7JRXsm4iqojrJ6v4rnrCxThTAZc00qOVK8Z2TGyE7wklRdfxqFqPbHc+fOOUbtKCPGz3VBfnlK6eCMnmn4W7roFFNosqPQ1kzVZarSY7zhrHuMGdb4JrcslP7HF1z5WW250NgEoSkBNarEVAx9zOPEDjDEmuvEtf2tB2hkromHntayYkoXCdLjcsTaJVR5tVwmWywU31vFdQip+Nui5+rAC0TTP5PPZ+OZL/zjwa+Ww9VQ7DkCyKJ4VZpgUQKkd/69Pt6Gw+oP3XarAJBCY8jwAmxZVmAxgb8OzGGw6m+zRqmlqPY2qjRORt+R+NdYOxUZXd/ld3+16/emyilLNCaUDTnnm0ldtE0P06I/AyIe6lPo3HK2dfUy1lbA/afDZyIGLygE/4AOKEXrcGeZ5mD6BTU0oF9S201DD4I1S6AThHo2GAUTZHne2MB39f2GaUHMMep+OUHVMXa6Y0UHYuyTDeG+TRIKx/AOjt0wlKBWmw==,iv:nbcHQ9mpIDZkEPq9qtx7jdBTTvjM4PD0gB+ogOyFUYo=,tag:4T3Qine65t4+fXCdDgW0sg==,type:str]
    user: ENC[AES256_GCM,data:rF55ZQjcflHavBhv0rtQrg==,iv:j5KvMJFEr4QjsYgSiyCIf/PhIwaLMkXanBQSDbw/Wco=,tag:yxuZeySGk+YpKtYve0LleA==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaFh0MXZTZHVGN2d4c2c2
            K2ZuQTU1djgrbWQ0OVFJVDBmRzlDV1UwRFNNCk1ka0xnSk4wNXZXU2xlRElMRE92
            dXduU1FwTmNpNEMxN05OeUxhLzBKbDAKLS0tIGRTMHptSFN3NWpwQkJuY1BVMWlZ
            dXMwQWNuMngwQjgxTmpQM1JiNjBYRHMKbKsppi7kgAosQ/oFZe4gwXtaG68ya4Td
            z4PdBC6ToE7wjGdi/tCfBK8D6Sv79pQVMZJZ4GnKYmRg2YqMt0ygeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T21:02:21Z"
    mac: ENC[AES256_GCM,data:PvHL8aCB3UBhUB+qIRuDy4sfhTmlSef2Cik1mrIEPWvOmT0QlrwOh9zM+R6QwU9eRd0S88yI6Kr0EThyjC5Yas4pWKr/srh6NOGuOMAqLYG1AnMVVoXpGDCBlzOaxXDfP7hdUk1IJdRdp+5uDsSS0kStFnsL6TZ6/0fg5iGZnOI=,iv:wgQPI2fRuGxhB5t2Ky13BwWXOi3bRhWiwYLUVzBS83g=,tag:kueVGnkHV9hz8wF6rqEpAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
