apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:c7K6BYsNMEx/EFqn+xaLbVpdeLMcGOh75Us2R7xOx20p02abowpmfMErW3c=,iv:HELXBXVj79dp98Z6+7wYQolzRRnuACx1SYsZzKPC7mU=,tag:qqtalUERSgN3tv4+4hytWQ==,type:str]
    join.key: ENC[AES256_GCM,data:0YHTcxN3Z26iRAk9E7HAbwmzRmIvB9FmsURt65X5bL0z77d8g+DBMFkv4rXO7L07kwWLqct94pawpienQX047As6ZeRnbn1AZ9MtpR0C5UN1FrWHMgulqA==,iv:pvwVXS5lZpAa07UuUlxyzhpwC/pUWSDplOmzktiRb1c=,tag:htUntOelhnuHaQg5W5nhqg==,type:str]
    master.key: ENC[AES256_GCM,data:RvEbcmsTdrIcIMhvXrRF3pDo60ca96K3r/rXGuH88rDj/JPFI2OPxQIWjku3SUB9E1gMrU2HP8EGgFPjp2p0XFqkCTbWNz6Z74n4B+BsRKPXgu4leE7LOA==,iv:teOSc0HleH0Gcl7ZYUESgOaNyz1A2/zlZPJBUmjZwMg=,tag:eXHf/n5i1BvI4v1Gu1Pa1Q==,type:str]
    password: ENC[AES256_GCM,data:/EfbfEaaQWVcxXIDJ4jPGiZxoWQI1ZR4QvzxHw==,iv:2V5yK6/uKax4ieLlR/+CKVkdEgneIq0zsc3Z7LRBS94=,tag:b1ixmCUfV0k2AkMT+UD84w==,type:str]
    system.yaml: ENC[AES256_GCM,data:CqING8pI7uXHN4YohEKzchTqgFm0YdkvM2XjQHTH/+ab8l0jaM+99WiOBviPMmDKls0/FPaF+uLrbFL4ZOuXDCvb8zxpiIA7JjDcCsCUTA7ZEHXr4UlsPOFE5LzBTgyH6wMYIInMpsH0RtM7LQGz/UwWZROhhrKMUBk8lykA/DsPGV51TO4IzqfM+L8Acp9bPTtgN+djtBbf9VHU5LtE49dCyqmY2j3EP6Wdyu2tgV+7tnylrvCQUWLgAJjh+2uWDUc2Y6Q1B+dYbJoancPBPNPlJCZ0K3qxts3ybO3zvX0QCb2THD/eVlZsp0f1y/rExJhClxFYN55hTFp5Bm4sT44fC2rk4atiA/kzbTuZ4Sut+eXoICFem83gXVKeujKtOu88oDzSf66AGIRRfB046ATBdAZuLLVUteJuyfh4JC5oQn/LHr0WNRfbsXVQ27Ajc5kD/MM5gbFHiXyf3vUgm+qEL6eW+dkQdkYedNfdG3k25QW1058qHYhJMm6HvU02zaUQZ/6T/uhjNnynBxBO6BlV0d31lTWzBCKMIY58ndcmweN3BYn3tA==,iv:0DIoxlz5XqMPa07MI4qxiJgM2y6qfbsN/bVSI7u2XD8=,tag:SkSAthSpHtrsUIRJxGojCQ==,type:str]
    user: ENC[AES256_GCM,data:aP8D8hJ2FXyEVOfcXXt2Ug==,iv:W7j8T9V6UcCJbQrp/KS/giMAMnDEKsoiJD+0xWd1NAc=,tag:FWq7rTwM3GE2eNgZJi8Y8w==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSnBiekFLRDFvcGRsUnFV
            eWZWRVpOY2N0MC9pWGkyOW1lNWF6RFhQdEVnCjU0ZTNuZG4yS0QyNGE1VGtEbVBo
            NHJwK0tWcE1LWlUxaGM1N0pNSG1QS2sKLS0tIDJNM3RyS2VKaXB4VTRSYjhXbUtN
            NVU3RDd6TlhNemVyTkF5aXE5SXl1dk0KpvC3KJRO9wOKFayybQ6g/h65iSJX/SRH
            u3pAw3vIVCfSWsRBrt/RlwfTO1pP4eiWikeb3mQYnMXo/4jhVD3ZHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T21:02:17Z"
    mac: ENC[AES256_GCM,data:tlQCvdF4NvdRivaZAxoMPmIStvlJ4GQ93ZN7+8E8aM6o/gJiOA6PIG+3S2oXUOxWyHKaSVPZRO4Qa1EvmFEFyzKbZs1ohX0Rdlp0cMguX2X0GICWOZyM/qyjbqFaFSOSdFENTxTYoKMuW+29wrv4+ztUAXJGtSxbT44esv2ysXc=,iv:7Mdy0Xly/UeL+H3VoETky5IpgRfx8nOuODThPW/+++k=,tag:ewQvge9kn6i1sTApFtIOKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
