apiVersion: v1
data:
    join.key: ENC[AES256_GCM,data:5BxRs/Oby3JgDVz35nSvPhN6DkYUbx5m86DFmUWd9L5oMoEK4V62TMtyFGJsug5+cUic3EKpSrMRjzS3S+bgNaevsxP0iIk23bZAzjFu3AS5ZOhjjbewXFp7tpEvHagk/9a8SJp8i5nVHqMXaEEjx3G/A9dN6ugyENPeTQ==,iv:SgqVqMGlfhoU+FNN4BFDJgWTkMbqNfXsfLLFfGMTeZ8=,tag:Pfzn04WX82P5IKhwk2cCXA==,type:str]
    master.key: ENC[AES256_GCM,data:leJZVrTFMflrVr9C/2r3cxs9muDGyMlbli53CcBmZ6KVNRTibsqOMDJWMXYkjpgv2tlTK78ikzdITOx8uOU3Jgp+EGH8LNVoMhgsYDTSpbdzgCa1s7lYcw==,iv:U3TeFZZowk3h1jSRNT8Kezxax8vHzP1w1SRDEGm6WCA=,tag:+okp6B1ov7tvzBuApRF+/Q==,type:str]
    system.yaml: ENC[AES256_GCM,data:zLp+OEVTe0gPvV8JY3SsoDi6iQVEqFGKoi8p5zbjKwGQtayN/AEUunKgLuxDsS+sHsUQtoR/SHRJLhOFBu8xxoinK4yZxD2GlEOVCmvUkVbSuN2EuToDcsI8HXCeq/N1CiLBTQlXWQC0DlOHZuemJMiLuNjBP/HAWrwllCEqShwk6twUaUeZf9Z65k9rStiTFIFEpT2LniZZeJUC5L9IB1U+CnHpm/9szefci5Ug6Yi64LDg9On0lTSqTtrxnc2IR1+Ae8mjmJTctPF9P9B4HPq8DWZcrnBIuK1oPMB2cUx96pvwxaLyQ5k7+kt4AybEEBF0zXdq90N8dpRQbnK4bxTaozpmAHP7rdaYUCWKJUeOXPRP2bwauLrJm/2MfOp3j+lbP/jAtJ0/qU2nvqeBbixF6Z3cVYlzR7fpbmhI8CyuZPHrkwXmCF9TGng2nbn2,iv:Ngh1QcLuKUOeJvDgAz4pVwBLThNaj0yb7TXVTpspNlQ=,tag:8EBhVJBp9y3UrDESpkCuvw==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZTcrQTlMbndxMkxlSEhq
            S2kyaTlYZ0c3ZEFoKzAvMWx1dlFXOHpWaDFrClluL3VNYWY4SzlFVFNwMnpLaU02
            Z2wvMUlRYkpydW5pc1dka2tnMytsWlUKLS0tIEtBeWF4R2NMN21yeENlRlN5K3pp
            dWVGYUhNajR0a1psNHlCczkvUDFZV3cKFBQXzsrDvfjIXz4rxUk2auV0E6q3l+wM
            6/ePW+lLiBHDqJexPdfNTmqtZinteNi5RiG448aDBO7CruXeOtGGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-09T02:38:42Z"
    mac: ENC[AES256_GCM,data:W4O1bqDowE+PymxupReUNCMnWadMvpZYfAorrDFvL5JmqS2b7QTzeeqHEmW7T5456vuaPiRWgIxwOYhCNyQZ4AqSG7bmKr26MBWbtwEGELQDl+A14hZyiw7/3WDV/Pw3V2QGMTMR9djkWLiCnCDuV6xaNGhjc8uFCXmWUI7rcvg=,iv:czv91fNvmDTcKykBpOncG2eParr0gzjpePjEKMYRPNk=,tag:9WIYB5zs9ih5K7reOD3KKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
