apiVersion: v1
data:
    join.key: ENC[AES256_GCM,data:gSti8pDhMHHu4jVA8KIMIXufT654o1twauCkh3rmKMuY3XWVwAi8n+0tN5mcaURGxYEKc+rAJkBw50qR0SMS42TFuYO8+Lflk0E6PJ3e5afSC7+DQDn4fA==,iv:EzBS5F/4IfDLLXQ7tppEnkWBApiFUpuxm/+UgCBskko=,tag:XCKrpJzPWIOUdmkM/vDNaA==,type:str]
    master.key: ENC[AES256_GCM,data://ZsYQdFpe7Qvj+piQhi/5Ut0Ji6xYQineIkEHvM99p4ID7sugXXe9Jd3P83t9JZMz9rq+jyYX9klz0ZsBEbId5+DuBf3tD1eogBk1N7ysthSrj9UJV6EA==,iv:b33RD9rMpmZgGt/tgTokiRZ+uQf89RKQzPZmMnvlVZE=,tag:vb64YJ/O5H6yZooM2IBHjQ==,type:str]
    system.yaml: ENC[AES256_GCM,data:gx3J2If7PiyFzMQCNdqTViQGVAlY6ZzIZpNBKFnVXoQDzjgVQF6BUgDRO79YoSKUZWRi3MVgVeBshyjmSswvyIXQhIS/dRwm32EWweOa3K2cX30+vcxLQfR9T7foc6XwPW6oScwGOC6AymlxJ+7VCONsHWYX8lH/bHhRbCZsJR39rIAwGg+1NQDd45m3y09G+X6rZSWx+Zq0nH+0SNdrec5czQVHU1GkmrcZpx6xs137g7/iSEIXzLRTpq3XcXbpawnZWXCar+jwQYyobQfT73tbRGNwjMlB2fO0zj3zBLo8E5w9okcQpy8t8kFvXgffzrK5gQK/G9qpJ2Hxl6tBictUzy1fTAFdnGeeW0pAlgAjji9fv5XwH9WX4QbnWaLhQBJeoK5umAXScve2dBd5cGXl/bw=,iv:TMgb577U9lxKOh/YjOsuP2WGYaTsHXMTf1zuJFZ4Zr4=,tag:San2bivzvoo4yLb5bh9Y1A==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWC9raS9UMU16VkpKUktN
            aFQ2WnFQNjA5TlpTR2RJcFdTRlZRV2dBOGkwCkhQN1BOZ1ZoOXp4SFgxckVQbUwx
            RXMvVzB2akoxQmRMNDF1N1hTUmxlQXMKLS0tIEpjbi9lNExJR3ltS0JYK05VQzYx
            WmhXSFp0Y3VVL1B5bTJhSmtTTmhlcVkKQ7u3JKWPf16QN6qTxBkWgKyFJqB4AbJq
            3NZ75gJ5v5bfx/kiI2DInX3TqObHulkAbRgIIq1onaLoD2jWnqb4Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T14:04:16Z"
    mac: ENC[AES256_GCM,data:Jp8UZhugMpCqqrMp5q5a0yFgAHlMCZBuYyIYcjrly3gJ273PJvXR64XgpBoFe+4LTaQ/A/cNHnis9LkuMmhY91xr/C9zyqiodYDkCdYUAc2PFsldgKGXzX6JQRUYataaE9L/+DoNBE9cFtvASz1ASLnX2bmMKS+IJTwmg+kr0L4=,iv:qOmdS/9jmUKBfWTgtn+h33RtHgvcNQf2l5AeWumkPWE=,tag:5ZENKww8JC8o6CLHN/V4pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
