apiVersion: v1
data:
    join.key: ENC[AES256_GCM,data:3sEYQDtyQAwakHxfLJLCAiYG81EpEOUN2CCTchB0idYXxXgU5rW3oO8zX7LAurrbZvJ8Gy0XEDGpvgRi+nob5t36pLUsM+B1HgSwA1Veg+aGxrN9B10QHA==,iv:7aHGSABs2rRv/IjXG6UpVYTfz9zb/t73SKvhvPQbAKk=,tag:JhQc1cVjIkzSdrTaw1LScw==,type:str]
    master.key: ENC[AES256_GCM,data:zSDWoScE1ePQs+JSUHdDotH9i5z10Ro5jPJI23PWohy7PLUxXrW2RQEpoOrAJeRg0yEWjROJEgz+qyQ3Km3qhpB44ricMvrMV1y2ARTsw8djNYtoubrSzA==,iv:ZZ8TbybKz2OvBJ4b9oRtc7RbHZ1yFMFZlzGLUNVm4Zk=,tag:q8Bl+XnAd5a/O7PcHfif+g==,type:str]
    system.yaml: ENC[AES256_GCM,data:ppE+cb9ASvlAX7DoFFPlPVMY/eK5qrHc1NAJFJtI/dRdbk/dt1IobieaUScFNY+RmhlAwW6cBLxD2768tRL8JvCAk7FAEz38SVV3+1EHIXkdy+4wKLTmZEKzR1eXDkav7hWYn+md3c7Op+KzPA9vamKxVmDhWDS7DgZOEBwSadEYL7uio+L82lR1UigyrypjoPzhWnGSnFuE/GOdNilF2BzN/iSyAFlhhw7kYhxyXk+/7GTEQ31nYHe0a3kxmhMRAcpAMBcarJiaGolJ5JsZSsp/xXSQf7n60p32AZDOXEtQzOipdi3KqVcuAbovB7ZU/SFFAEPUqwsdkjxskHV8OOzUY1wJKKFL1bEEeTnuofiGY1itd/y3Bwa8/keIIiPQYJGDlJGH3Ze/SU3riXEd+Z1nfj4eUvGOYxjqDL8K0W86O2NS3lTfij7Ntr+aaq+U5/3crRWHfU2LZV5i0k8AU5PkQyeP7EoHxWv+alZoH5tD32Gk,iv:EkVmNvTaQoIKNyw0U0hBl+7bsAfvEpp+uDzBmyrLzWE=,tag:Op6N+yl4rCQiizEiuRI82Q==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaHpyeEFOanFRSXlneFp1
            RUpWQS9xSmtuQ0ZvcEVhM3huYjA3NG0yclJZCjE3NWVwK2ZOSFcvVWIxbVJ5MWZ0
            ZDJmVEg0dDBOVHFiVG9obEEzWFNteUEKLS0tIElBaHZKdytnV25VNXB5bHFTZjAw
            bTRIbnlQdzhRbjNpdDRQL25HbnNOWnMKvvZwjmfpAu+1WP+uaLwe53dIbdfESofm
            DrO15KyrKjiAW21HgpRBOZ/nPzY4JmrELsQZ40kIqrIu21Xl2vNSXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T01:37:02Z"
    mac: ENC[AES256_GCM,data:pMICDuLRFkgC2cwCGJte82AwfJipFaTKHY2RMbbF3GK6Q/7n5jhj1h+lcuP5GWAj474PxoHyAkvocWuR9BMsVR6+isqocSRFZqECKpohTmWxnTJ/vMCnscLNlUUBy/uHELJ1/Ms1weGMSTnZRUcZGbl5jN7rEVglXgW1ekhVZUs=,iv:rMSD6h8dU35sWKoA33sCbGW+bkOn/q/5NDyT9b45O2M=,tag:V5VeuMyzLtVsnsVQXJ3qBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
