apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:J8K/T6/54XoQ4NZazK4Yp8gDAKX+pVTHZRQhbWEFjdfOgWP93mBDgPyqfyQ=,iv:coQEFD3AzGfM7KiEVRUSFZPM5agzlcvdetHoc1LLfog=,tag:0Ml5g9tCkD2FBTUNFtYlxQ==,type:str]
    join.key: ENC[AES256_GCM,data:pCr4yZxp4XU0JvKQ/WB6axbxqS7B6qeXdSMW16VZDs82s81t1yhSkIbwWHceCmNnR4aUGLrt4byTsLZfH4/xmAluPQoXZ+0tMMhhVYZOsAyuBuCfGu46QA==,iv:m3GgW25R2tbvp0kFBklkj21fOZysKZ955zgU3jtubiY=,tag:6iMRtYbbT8RZf7fdUnH5tQ==,type:str]
    master.key: ENC[AES256_GCM,data:mAaFSYDHoyHg7QV64h0OrbTjL6iV6Azv1e93tkkISzcPOPzIn55uA8Ypc19b2tX5ZoRiL9i45CviWnwmz45imG/NU5MEowH8KFEwIApeLSoQDOTmkB3X4A==,iv:UsdTB5K9AEhTiVIQk050xoKvbzyEfTiAdISLbmkDSb4=,tag:ilcFBr7s64QbvSaaxOC5BA==,type:str]
    password: ENC[AES256_GCM,data:VrPZXis4AZJFFTMGUpl1aqxDuhSHGKQMhkGjlQ==,iv:grdA04YyqxOuXNcikD0XZrVPEx8lsf1Pf5nsvkAvqgk=,tag:adzK/dSeQO3nbHSWaK7P9g==,type:str]
    system.yaml: ENC[AES256_GCM,data:LxY5gp9InHqPrXtJo5mIFpg5dNAsa3KByoewgVGgG+9CxCiE1wkjKd1++yQoQip0cADcMhs/8wLXik6zw33Z2gJMdfSgFPd/xG74OWUs6X2slgsAQGAzQeedXh91pExI7IRsFqTiHAlH6YMBBWdIXcqXwRgVUDOWIIepL93yHmBaM16eb5JDM0B0yz1/heDx5dyBPiwB0oPYbeO70sdkn7bDuSmUNVmlcqxY4Qt0k/U9SgTp6baT4PeP0KfJm/s1aG697Daghj7tR5cyoLpAFfojudiUoOkSjQwEjyv9wn3e+q9GgCvfzyFiKJ+AHTfTdeAmB++GcIhNJWtI+dFv/qJxAdAjFXiNWldcTwtizf3pLKCduj8u2Lk+KLSLCD7VVLOi4uG62izoF17nnlT3xJFpN7K2QymH3zed21OSpPtZR1pSAQFFob0cIv8eiS4Wu6I4nZ+MJVIE+XCRjuV/Y0y1e8OoE9+q/NLvS1sVxulwOtCkOl5dZUYi9jtIiydceIoYn8UpokZNQEwvQzSQBrsRoPTDqPvJBjfkDyK7Eia+Ludu76tGgqm3i+xgjxiFx7MUlEpmc5SUi93WiSjqxZizHmrd0pBngWoVr0DWIFOPBv8yLFE+jJ3u1Dp/egMV22tg0g==,iv:hVKvyrIBh9BZG/m3mnHEcTkkwv8j0vfGE0fjNI7+Gp0=,tag:Cy2PaOq6p+bxrRZswfAVbg==,type:str]
    user: ENC[AES256_GCM,data:7eXrRKHQKNC84HueF2LBUw==,iv:e+TBzg0di+cuI500k64Nn2+7grQGQpZqJDbyLSiefWo=,tag:pGI1esyPi/Q1nCcZJ/CgQw==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadlNqN2k4TVBKSkNQQ3hC
            YkN1dlpub0U4OUdRSGJqMjU1ZTE4TzBZTFFJCndFVzZVUFBINHo1VENpZENyTkxS
            T1o4SUp3UjZ2NnJRL1pzVUIyL01pK00KLS0tIGduS3VzQmc0bGZMRTBNaEZhRUd0
            MDNXU3dUNlp5eU5Uc3BYMkJ2VVdIVEkKu2Mt+diSyQYSsMula/bZ79k4fwqe1+w3
            s9A041REjM7/qOKaYztAWNwudK6PBKoKxNJdmIz5NQTQc5oP4dm6NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:32:52Z"
    mac: ENC[AES256_GCM,data:AfwLAsPvrfzo1jXkjVdZA6TccgslgTko0AL4J+y8TgbizMSYz65fFquGMWBQbuQZeoiM5WKqC2uQyNG/ndFOGHd3sV3Qbh7++0SrQIdUlewoKYHB9BZ+/1OU7v8Dv8aJPF88WaaCoS1oa0oq6yY99zz/qgjvRjWb96O2K5JIB/s=,iv:zHbuubQqAv2ysbnIMrI6ykQpg535VmKzkVYoj9jGD2o=,tag:sanMVZTsnSHXaaY/cbbNIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
