apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:NaaCoCOB5CDcpBclhiegTWHAllIQSqoQA1uAlRetOn2b8WSTUuZX5Onw+J0=,iv:EhHkJKANmSoG7oZLhyRUKWWQu1yDi1w4sXezhZaPE8o=,tag:fpeBVQ2NhyPDC5cHASvJ6Q==,type:str]
    join.key: ENC[AES256_GCM,data:2Tq93vfpL8IjIMU/0P0go7f/gOsOHZZwwxe9X5hXzg06uz0jTaeO3h7oKmICW76nTP2jHhEkEAwZ6j5s+sbdx0bPozNTrcCroc1wWO4lVpcTDRtvBJ1Xhg==,iv:D3nqVv23spXcI2C8NV+3eSlW9ViUAEGnF91+zdU9H/4=,tag:UQ6M3H6Jj18Acrp+x3VGtQ==,type:str]
    master.key: ENC[AES256_GCM,data:cZvGnQYsWlvU2U7l4zsMe+scfVi89ZV0fN7cDcWF/bsO1Itpwufwf+enelpKoDbj2Jin1H1uHjPS1hoDB2pUkcQg2KQqCDPQFiMKLP6NbAOVzZgLfCTAcw==,iv:C4Bdmxxw/2489ZYzc7A4Z11sbXph3XREyqEcwAiPXzA=,tag:0iQtq+dWXtmviNAffV5pLg==,type:str]
    password: ENC[AES256_GCM,data:PKaPTRFycYgf4rEQRWbwyMrcmK9d26yB1GsCLQ==,iv:4WxTdKkdCcrfCSKN4KPO8svkT3J4Y0rzynUsHl2ypf0=,tag:nd18A/QZ/LFHHfgtLICEqQ==,type:str]
    system.yaml: ENC[AES256_GCM,data:GnF5oVgKfqbYmrh/buUS86okLATEysZjI+P67VKE/f9uRZp9Ub7DpcR5XDbhkyDwaMBCR/ulXfoiBgCvkt/bO3ciu+nOQrtKxZEDvw+IpNzGaq0S/6AdQhHBch8ewMRU5X96f3EuSGqIkCY75X1MBrN4bTLXh4Y4Q/b/ahjOBk2FK/i6q7oDitNDuC+c3pRDpFhCwx8H1K+BEzcdWUU9klaWcd2EYdkwceE6MF+R2TUxKHdRo1eFAIBKFG68JWfKogm5HzmayUb/0Poi2Ax3Sdi3nNb4eRz6yTIL5j5SqOZaPnV8wMPSmw0hCeEkb+J200LirtdIDMuvJztXQbx6FnoEZFhNYtWybYCeGyxVGZWaDkkKRr6u02rELftX4QIMlEPk3jAHAZoafP7QIaD0XIiPoPgnv4T6LUm1gRbsAB649sgP7LFgrz+oC9xrZTOyxPA0STF/LfJRqbATrZRe3p7bJmHpqZMtyxsiOgERHWywDX4m7nNe59OjxGnodfDZ9Snk/h4G2x9zg8pUU6Zm8HYOm8QdMS88+0GXiITbRWUIS0U+yVg7S06Rpqfx95iYqtruLTVgaAr/jb/o2FOxx5h4Lzlv13j6DDviIFTCtH70lXD6N7vA2LT8dCo9O/vAkBgGhw==,iv:0pa7kaiJjPYJwc/qcIduXWHKWMnnrmYO0RfdELYRQpE=,tag:74JCG+PupTz0WBYrIUe+eg==,type:str]
    user: ENC[AES256_GCM,data:mDBXl46tN2FhQVLHuesZIQ==,iv:Wa55bfWEvGaStQg/MWvCnXOUetVghdOaTzCeMXeCLG4=,tag:DtVzv7qI6x0ACwa3YQFkYg==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobmNueExqMVhnV1kvanlM
            S1FlcDFpeDBLVkZDeU5pUDk1cjdFVWtYeDJrClA3UTFrV0lwWlhYanFIdmxqZW9n
            YWZiVUE0VjBEbDUxT2RRbUt3OTRlRHMKLS0tIGFWOFpEdU8xekx2MDVqOWF0UXhZ
            eHRRdDVOLzdSNm84cmZkWmNpZm5tTk0Ke3axlWMb4ePW7oqwJqOjxBrNlV9+w6uU
            g7s89+Yo89c3So+jK3kJlLIkGxWpaCYmA87xnTpu3FZRLvUijRsaNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T20:11:06Z"
    mac: ENC[AES256_GCM,data:UqLQ3AlTMKGLAN0g0uqLDjeM3YvKWlbVOYFSvlINztaEXtkblhZAob82slRTpy1HFsnzknDni8ll3zNPZYuLAygaHs6mdoV8Fhux3gHV+ELkbi1VUYoaKDX8sayGsZlsGPwQeXQiFVYzLZcc1F0EGmxWKHDbrt+iRFaroGLzGTY=,iv:7RmcICAfLkcfRXOOwdPfDzitlns0W8NkQyzA4itoXAY=,tag:92EXOBAfTAMw7e0Nwol00w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
