apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:vM1LZWcqm0VsUqC6JOZq2mZN/crL7VaTTrmWs3BWRSmgRqfD++bUy149fVY=,iv:I+OVIg+kdCPQZKKvuAUuk1cPu28FMDUjeAQCM5C6mFM=,tag:D5xygARQsugTVeEvlEqZEg==,type:str]
    join.key: ENC[AES256_GCM,data:gV+PT0yjbvKnt4IXkDiDQnaGD89GETvhyhcIGRQo05oxrr95j3aLv8pIvxzpii99HhBruhQCvcbK6f0JL3R5uUceqI3Y7MLPn6FyFjiS2L5h2ux65ejEiQ==,iv:ieRVRQ8RtOdFkm9ZBcu+CJnDVo8zQOtaPuzbigPNlD8=,tag:90UfkXgr6CkuFQfPGpl55A==,type:str]
    master.key: ENC[AES256_GCM,data:jfL8LyMiKhw2SGt59iywu9De6XnGVJE1iVy1GcaPMDDmeAX7IKGT3btcyGdxdkjrxs7Y73SZPLQBoPu0jpnN/sW2JUuy6jragvYyINDfFi+mO4YdS3InBw==,iv:Vjd+DW7WOVGPEKTtfkZ5LKonR4+zyxpBtzJb8Mw0PLs=,tag:MO3iD8WssPZom3jQpSQQ0Q==,type:str]
    password: ENC[AES256_GCM,data:QtNlx+uBTQ0AaDy7mTBxpn0gTWqREa23GfDK7A==,iv:2QI0zMxely2uX7fhr6I9okh/ijMJXRRq+1VjJPfyD4Y=,tag:+4b66ZCi52d/WG8BhTYcLg==,type:str]
    system.yaml: ENC[AES256_GCM,data:qSh5tlukQ82x1LeBuY7V2DYMp4aSGWYyndfvWKTdkevTQAhRxmzwveNEP5wjAP8sQOwjc339Q13z0CnQVhJAqVWbLVzNE3CD/dQWIl+HDW/4qMiL5cAP1+ZiqykwcFklJo/wdbM69pwMIAXTn3rOr1MA1I38sSXZCiO+PPkYjkz+ik74imdXGNRuPs/N7vyooauzVqz/zmV6DwVe0MuUBM2fPS6+pdOLkTSJkx1sMye23S0fwHgKTzDaBmr/R4RNj7whKDDdUA3NSYNEtjX5m9gMppNpM0S/aA6g4R5mrnxLxSVrDYdPwVtEWExs5m5BgFNiz7CZwpOpLsGfUOocwSlnBjwEMawIeGaeeFaxOyGnLUWbsD3iCHEbp3N4T5f4mIJ/bmxjFGS3cXaIZT+3WoC7YlFOf+dB+qCF4v85xszZOfAwZfdJzAB0IlH41VPyDffh2P3Rud/OlXXLLutqo+CnxID+Id8oGeL84X06qMoPoJaRb/hYyUBA00i2o00aBbKZAXXjNpnFeMcYUNa4LyWkxrydYIxjsHlh5kSQlLQkCt4yhM7HjQya5D/2gNgUl2ZA97s7mOSWYrygn3onruxmCbFUeLRoYQKAcoli6pP5+71Q+g0UMLcUCfL7GfB0UxtStA==,iv:pI24DJGT/el+0veJT169gYclZFoOT7x52iWBTrKuTFM=,tag:yHmQO0IGHLP3LEh9i/PfIg==,type:str]
    user: ENC[AES256_GCM,data:UGKCeJQis97kGB2oel8tCA==,iv:IFLyBp+ZhaUBeJZzMFUTbo404/yWnV5QvBf8wwpfv/Y=,tag:tRIoqHhMIbOrQIng33yscQ==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVlpVWFdOMmNQVW9zanVE
            NTFWTytxL0I1Tk5kL3hidHo3WUdFb2J6KzAwCmZoME9PUk5RKys2TGlzSHVaOVp1
            TWZLcjkwdkZObXV4WGhKZFNmMjFVK0kKLS0tIEg1VkRYZ0hvV3UvN1FLdklrWFl4
            QXUyUHNhR085dWltdnJyZ1diWHZqaHMKIJ3OHaHkZdxwMYbUwjbbRV2J1JqGaHUe
            LxdAdL5+pTFrkAZP18I3Dz49nioOiVqhEM0BYGc6tR+ZxCFDhEmlFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:32:58Z"
    mac: ENC[AES256_GCM,data:fK6DO6/p2M3maZxaK65PFVtf7wjJv+cfhOyUxbH5oLUBnFR4u47UWJ8SccW3fLctIpdKc/lqAByrBEih+wlhVxeMfG9KNbDl4bZHcftVD58PK3Yj3F746GyrvQ2PFE5PuJF0ji5VAga5oRa+TT3ZmJy1QdTdUEFq5VSSE74AqZ4=,iv:QCTlXvbs27+E4i0Ukm7kd4H9XymXajIipHw/H2J4R9w=,tag:NNhHGQiQFLbmuS46hhRhFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
