apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:wc+oVxzYX7pxDMHtRMgKKyXx237+YhHFfRd2ypl3FoZpMBhSFlonTEbx5ceOu26w/jAprhhItdKnEsTE3XlkffAQPCdP1LhudEgjQnROdbc28uDHqkNC5/3jB8te028rcM++kKgk6akR3xo78LFOZoFqDHRS3JUeMqmDII8oMvyTct4SAXWqjWJx492hq1wHvemnQSMHbR1TpxpfPM+VI7OnbH/XLvwwb9G2Klu/bsWOPhtpOWDepWjtC7QzuCYhxcCCS0kE0oUoqklNLZcuAU1o8flGDeGUWNQ6GUAR5ScwpEavr3yjXaRV59Jc/ym3yb9WVKmkoVL1ke2ju2j8c8qXs9MYDXi15XxGAKrkzTx7Bxpu6PCvM3WuF9ZMaRnhEF6kjKtbFu0pSBXNWgaXNtPE+CdNmu6uGYKtSHL5wowI3iSGYyVWlB4wQnDqK6zLKi3v0FuYxiEVcPxOQBPiGQNhiLmjJ8Hs9NONbFflNttqrzlCplcJTg==,iv:Hlo50inI4bRGKSOBGbsWdTw2CB/BNMvUObOGtR9qBAc=,tag:fKbrx9e5sX0l4CWOY4FgHQ==,type:str]
    config.json: ENC[AES256_GCM,data:4HjJGeYTB0hZPO1JMkl9ApFx7HiJ1hKj5FwhLXO0zcey7s9lpoxp/tfoC8OAGIXvny6XDBWJZ+aBK4MXRpo1DNzMy76rqtCgw7j4CiWlpGiSbAn0+OXEuifMgGLPQxo7MTvDS5QJ/HE7Z+zAoxJgjdNcPQRqBaBFE98doRV2b9wVh7hY22RFuclFLnuLqqnbUzd3Mh19CDL/yBCCyKhxIfH2SZDwl8Mc+eaTBdKWCrIq3V5ciPQ3Ws2wJNu9+DYDkCcDudml0jgm2faTFd7m8MXc2oZzVQ6QVDuQ6Cvm6kjI8jRjnNSY/HM2hBTZtQmjAfm6lJRGQ8Odjb5MB9EhMNykuiaLzSaiCrXPeqREcG02tac8Jalj/HXjVSc1zyYTdTEy+D6NfE5MRqK2xzUHirjae/RSjjsz+RgJUlG3b6XqfXhowdd+poAmVBNhmF0yOXp5OsXs4ngVPGLxkA9aL/yW212g+KF0V1uKRq0HyGk+KM28icxi1A==,iv:47kUDvAXAZmXO3+CmwOMovkQlBdqfdiyQBWFf5U9sYA=,tag:T+zKixgfDLWbQVwNEwluHA==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: infra
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdUh6YW53Z2xFSHZZOWtP
            OWtGVkRMaW9nbit2RjU2VzZ0RU9tYW9XSVJZCm9aWTEwMXY1ZU5YNGM1MjcyWG1P
            NjRFelFpNTVMRU4wOHYrSGRtRXVpRFEKLS0tIEhTV3YwbWh6ZXlZZmF4OEg5QXVX
            MEJOb3dhK2kxdHhMejVLQ0ZwQjhoRjAKFdP02lbwlWWeM7EtXkGHeyBLenyPibmB
            6txE4qEXm317fAoP2zVVC0wNVd84cSmQFbfwve4JR7Du86LsI1u8Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T03:38:15Z"
    mac: ENC[AES256_GCM,data:+PcMwk4u9oU8SB4Vsjzve1dXslNMFp0YSXoHfzR+5JASWyUYcDefmldeEP10mj4nOI+wNqlDsMAsxuk21ux+FzUhccOtmbvMYULYjRJut50fh52mFx/Y/ss7nyIuRwJyMohPoPLrQnl/YCce8geUSxYicmO3XBA3wRoTfQsdw30=,iv:MtC3Nt+xMIqnZwOrFJ+AL7XVLUVA5k0jrsva8Yv+pr0=,tag:fL4JEw/dcl3t731FSHQlLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
