apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:PDiP0y3JJ/d1DamQX7wiYQSO2oqeydspBaxDyN7OxdaZnkefP5yrPaurkoD+RzaT9zaLvUF95nT9oxYixogPlxJsM4bYiUn1gZSOY/+92ptuHOs+B7wuwqddawVCSpzUk8B/2nyWvDuDn9qZtO38qQz5LtYWVx5u8gcbOWooQTZNsWUhjwMIbGxNQPJ7H9Ds9Fb5TsfTZOQquh+yaVHfFh9r07nrjD1VTUYBCUTTeqTaCvR8bsk0W08DctaRJ20YPP8b01VVjnYyC1iuIv3HvlNlQX2zY32baxgxd6s8ptdcdfGGD0yt9HqGvvfCiyfqrAVymIH9QGHiNRczGXb3CPQhHLqlSrVanOkcb4X+f+gA/+nl/xvRHUq0pULV20/k+0SEkQ52kGs/u7qML52DgbhDIk1C2VpTqLf8N/23iO5ElSP63qZIQRDvZ9NhmtrP9IOW/PkCGVbNItl35WXpyzqGqoD9OmhWADare+ZumfWydG7Aq9hu2zvuSMFzkJ8G10MKrMqAVS3j2x8V04km/ByJ0ICzSAe/JezHhbkI7GKnEd2vD8qXRf8g+KrZX9sOH68Y46aDDlVbWtDhrxlZwxfwabZn479lyU966A==,iv:7g7n4o6j6IIQanDsdRWzWO0uqE4RmzzX2HtxXdtVRwk=,tag:dQ8VdxzbcJnJgAeFBvOAow==,type:str]
    config.json: ENC[AES256_GCM,data:cnZ4BmqJGZEyNpYr10xgBlwOU6dwJEb5AfXJ5lolZxgy5Z9WFNkrv2rG/qasGS3PsHD3Zqr6SVYVl4Lgs1P6x3qyltikFHCePO8h2aJEPzYtvDkNwp0S/ey5qz7Z6jJMtzUZU2/4RmO+BDzlahdyXLUAl3KooHkmlrZ5yr2L/oMQPDNRT4nLKNgX6JjcedUfK53Wn1Af84807J7GUc1Z8tF1iTNT5wEVopPfZ3SWVfQjlAkYeEfcA7TbapKWjQNJ9AI2XbGsZ2y0yxjbvbF9v+p2r7wUeyh1kKenuu1cgYssK/bW1g+GOyK3/TwVWnUD9kB+DcEiYYDJwJkf/cLyYXVgbrQtdljKD/vJ1Y1zin08OirbakXVSvAJ6Ho0A7m1Hev7W4MLJRo5hHxVDHz6MFD36/36VzqghCql+bgr+bDVZt1VOvOp6eE/hPmR/UPcPbpOqaQttXeNdmbdQIwJt0J1XkeJsFrUq8XVb2/+8V5TrdHQPRfXF2asfTTjDJRIRmvKMMZL2D9N4Xp8420676pOxLvVYoptPizSMmUEbkHIds9XtMHTiF2VtMp8/tan/duMFaM0YLPP9PDlfgQeailCNTuSZnG3ZRDapg==,iv:l/+gLrQrR9atM+r9Afjx8GKnykq8i64kxqJPKf1/8YE=,tag:6vQSFiCygekgnd6O8gWUiA==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: infra
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZEFuRWpDbGk3eHdUOVR5
            ZmtVNmhwcUh0T2hsNlBFbXhPU0pLRW1PeVdFCkN4WW0xTGdNcWxNVFVHcnJXUUV6
            Ni81Y25XNHNGWFhPSHBJQm9IZkJFM00KLS0tIFhLQ09ONU4xYVFyTnN1R29pL0R5
            MThZRWJ5aXVEd2pOTHFqRjR5SS96T0kKSpweQEW50II73Q0tgm5Mxv/KOiB52AJI
            A0XadwTw5ezCAa2bfbrMyOXbvc1El0L+jwA+A7mQXIiFy2axGh3V8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T20:12:13Z"
    mac: ENC[AES256_GCM,data:dtLx0kMfIRIgkD8KTELK/1o2RKmArL+EyFo4uupLqNa8qrm8S10Y7RBXMynbLHYwpu0ADXUYpVtMXKI0EunJnmL+SQ18ky/2HE2PsRInFWVY0w2HFpowE+vYgaGpnURuR7wbhWceuQTtJJoHqzTiNHhHQf5+DmWDthARV6CVBQ4=,iv:xIYsg50rFRZDjwhi4TDfH/56S5CE2Qdvl39FH2qoiVc=,tag:JhFe7unnO8XVbL8vNHRKAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
