apiVersion: v1
data:
    config.json: ENC[AES256_GCM,data:sEF5DWC8wWZMoEGYLh4sQKAxzbKxj7G3CNINFIIGApiBjDxqBqa9p11an6m8s10/rXnzVyMLpEROYRuD5S+jwNSqi1hFaPazIS50hqKa29OQq1RasZBmznOkc5l1WSJUCzIkXVzzmgeJonkv1skZCRWZEpYwPjhmXu2zEM15Mm8FgU045qG9XZC7LYJxummkCT8E9PKUzONsHi8t6ijKbXC20KJHGha9jIDaxZ4QCH+pSUY2NL8dkc71RAn+pLNeSCuutthvDaj+/zPDBE72NM43YqFHAHD9WkeQqNokVUxIEiDq21lmIvyj+p8=,iv:FlTnOqLE2zacitUo23R8NIUCQwW0bJx8JcGyuwAsafo=,tag:J3ceFLpJIFg8eR7RNXXSWQ==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZERYWTVlMjhsUzgwNHNu
            RHFtMXB3aENRYzJueFJWUnEwT0trRGZsR0hzCktqQytNVzdxM1AzajBkMzJqN1Vl
            SVVJT0drMFh3Mzk2Zm9mZnNaem5DZGcKLS0tIFBZdVVPM3g0eW9PdHNiaDNaZWQx
            a1ZQaEpUelFsNVlRZ2dYWDJoNnpmODAKgrEIflDDUbHwNBN037BQtKM+esXvIZqS
            Y2pq7lHkXZKHYWgqpaez3ULyLQCDJZQTd9HG4y/F8uKRT8w0qy5yXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T03:38:52Z"
    mac: ENC[AES256_GCM,data:4Do9bKiKbf0MUkcft04paQaaEaz7qAO063HJDi5/rG+1sXTevbUMigZD4w8A7jx7marjPSJLGORRmmSBmg9R4wM+0gC9K9bNwbQ0g8UfEDEYveQ3trklC03E8iLSyMsZsqF7y0+Z7ffpYdgJy1hpp3gJ1dZT+yWjWJyZFK1m1/M=,iv:ghuDJfaPTKQjRxKfU85oLeu7XXpGBHY4U+Jq+6jxbmE=,tag:fzpeAWpnGYWw6T7Lt/5iLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
