apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ATNrSAO/girYe3Jkia/KKyo0tx0OxtAxKUcndc5BMPyvJcO6tb5cNqiIzxVPCp/ZC04vvUxNa6n3WHa3tow4a76DkPz46L8hFqoiWXwjnM9/j5GncoRbLGtc9oVSJklQ0+O9h/w647IPeZ3Fq+DTztyzKumrRfY4xWzSNXHNrgRUgQd/tWQx9LL9PEh6FGgv3MueE05ZS2bukwoPUTiOghyN/Nmsvmiio7xzxKLXsSbgbUPruvMmVhK/TB3lr03AlpKXrJDs117vwrsuXkl1Z+ZzC6wfwOrctwm2UD2vW6gFO6tlBh9Mh/aEXBFRXQEIXJXUDH4Yk7k9iqnkP93X+UW7sUxu9ec0mpBqocH3X49qFqcbRY0tQxYocX/gAYB9mh3DmrYxkjLC8jXxRDNbCUafdFzZljRfLODuoGGT69/ocigiteU9bVa2hLGRGeZup9etfq0co5GbpZJRfA83lx2LXBa2cm85nQgZs67FMXZ9g2Sn+ZGeQjnvZVD0ei8V6RvY51hbDb9f1xFiAOsKOQTiIVixXIjCi7EXe+hJKhKxl4FR/LYuVmxkVrrcbkbuMWB/T/dMyTqV7PO61LRphRDzlfQYMBUE,iv:reQCx4XlZ9KyOPxJJpJOfssW3x71AnE93xT3jeiqml0=,tag:aK83tMCyr8zUAgqFKJPu2w==,type:str]
    config.json: ENC[AES256_GCM,data:vp34cgn6g/ioZ1RP0GkyhO8vlYIBBJn+lDEProCYb/RZEB4oVEZqOJiiB5ZtICndFo7khV98wncKrH1kwABuFjmRO2zMJqYNckBQZ2mmGnUKtRnCgBSwSsnkn8N8ibiNSUqmQE0ZB59Du4a8kETDSDFATMYUombuox/NivJda1RTyMFg0JstKPkuaD5gWJAXNwzByVPt+1muFE1Dvy6v4BWzhOiKdFxk808E1B1DxybLYt1HkndpQLweE8mV1OMx3yA7++Dequ8J0YODwkac45hlKISiCE0+Gjdir9XV9+Lp1hC5egm9LIw//YFTllrdtevE2gvm0pPRJGJCkofVq/JtSjJe2JAP4AlZkw58Zptrugt1ey4mhy0v349fM+1Ui50HV1fYYSLOqoUOr3Fmm17Z4jCoIsIu7++BOfXV7DOolHNKTvOktgLwey7BerdDH/E0aY9Qhm6OP4Tt8upQKTKaNciaKDBaZwJAONA4GsV1YXrX0IAkjXccx7cMHI1wcMI0noA1KFG5PcdxjYja38tnp3Z0mUETVHgF+N7L0BsU1eaywqyhbChmIVDZPeVDMtwCcgy2elLRyrR9qgjeoXgZP8sCaG0V,iv:13KrG7tg518AC6Xe62JfhHr2rkTjmEVwlH598eiTBPA=,tag:Qb0V/xDqYlPh5D9wMMHxSg==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: dev
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd0VPMmlWNy83bXZiQThG
            Ukkzc0J3dkM2ZXY4ZXA4MjlyeC9RTmtiUWhnCnRVcHpLWTcyN3ZQOW9UNTByK0g2
            ZXJrWkNHd1MrUHJLOG9XWFJPVmNOZkEKLS0tIG1uVUZLRG00a3BsUHpleU1sWUJV
            VlFZYXQxa3lnTTJIMzRuTjNpQUhnY1EKLK1RRSEJE5fOJ0mpnSIE5/TIjcqSvZkx
            HmPHy7G+UyJEFN3OJq0pG9FKwXJOX27QjsVF38pv8vPykk5d/rj3lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOW1SR0VNcHVzbjBROFNk
            anNYWldKME1aYTZoMlNtNjVWNmlXOWU2bkFBCmtmSExSYkdpeFU3Q1dFeVAva1hQ
            QzE5R1I1cTZNc0Y5UXpaWUpSekkvdXMKLS0tIGx5blJVRmZ2d0Z6TXNZUVJtUjhO
            cW9McVpIMmZYc3g3Z1RBOU45emNOWjQKMzvg8BF53pMJdbCJy6NmeKOrIQua2y4D
            BnRnfxHdmKKTRXBzJT8Sh5X4FgqqcRGUh33Yc+mDR1aH+A3khK1TbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:12Z"
    mac: ENC[AES256_GCM,data:IeKCfOemH9HvXc9SrYDtQ/s7Vtrov4LK4GQr9t8cO+CEaPaLvU72aSLVVCKhZ3qTRvOgqUyD5DbM+Rnjn47RFrrxauo0gWnaAXMf9oCYLpa7bZDO1K/bXSI6NjuhFRSQTWCdJmo12LiCNY4e95uA/83hBVYKtIJeKQiuUqT0qYs=,iv:/8DbH79Y21nepspvQ2nqjkVTo1T7Fs4Au/d2lG1Jifg=,tag:ROfAboW0lMgkoj+AZw6TUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
