apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:o4q1yqffvDvrT9v9VLwI0xa+iGn9osrMIdxsU8gBOerqHIM7Rg4wS5Ky86KMz/ielSsGoz3zOjKZk2vkbSzWt/aMlt70c7YQ/JUU8iKda9xr8vl2zGRwYnrI8+BqMq8Q8f6ZHoo+wacs3elKZfw1wzdaAvsi0KeUFeTiG/ryDn0f9GZuhuyY/BD55bHcskSMSd7dSNXzW8rU1TdareyxsejE51Ov21+9bJa3miqWS+RASGKPewbIF+/m7BBwQNkgg1Bx5sybvsTpEAQGVvm6Hu6E93KXvkhsAg4cfKlOvOGR8ltswvPtVvHQrGd9nngCi0IzGc/j5EFihW/J9cEH9t6t9rz4hVS9XQ/oSpboKktsmHkUOQJIUhqVxaF5WhvmtNJ68xhxUMpV7yp6bqWMKVqz4UwW7xqfIxiLq73dcdlNAZHsq4OJ0cQyClunrleeSzh0JQOCZMnoXs3916yvCUaVfJVvcPITV6lRJHgvzBQJduXIhfbK5SFdBb34FV9ByUgJCXN53f2klvjx8LM4SlxgznZWEdPelNZ1Oo2gEKp4+MUeDzwcAn9XgEHX6Qe5r9LBVyxGb4Y5yCrNiUqKFf8la/81YWHHel/vNg==,iv:utjfplE9kdCkBcse/oKleVY0kOgcZIDxUueH+9YKXgA=,tag:dPLRw4cz4Fxhk7d+zQhyCA==,type:str]
    config.json: ENC[AES256_GCM,data:GdzgwoHrjZHAxcvLOoG9a9s1MNm8Mp6MXUkHK9NL73abIKd1Y0bRsCHO1hbrCbXpMz4IG6letCJJJbJpRxZDoLMdBpTTuuSPkfyPOpfOGXe1dVB5zOBrp791IENuOSM+nR9EyDPvVrIm3dh1GHC0+9d6Ah3whsD1ij5B/QBBeQFYcyx/ZonD07AhMRiioEbrRTdgJAWuNfyyBx7Ib4pfvULmpL7A5IdIssqeIslFevhWjem+KO7dJiVEyp69JvgiOUBiwss6luOFbLLfHQeoP2M7yMBR/aO1mMiQDuF13Qo381rASHlndHoFztG1vh5boXKElNqMWuL2sKbKNv8ie3EW4B7TSRfARA0pcq/RLEpsEOlxJeY0XZt0NmqNnIBCrZmogGLuiQg9BAO1AuNob/9aL+Vy0f7mvWTl4izYq9eu3CKuraIsyxfmkujISDEoYDEJrPtOD7KPKs6LcMeLefjlwtyvku2t2jLsckAp01bHba7kR2XPbVycXSNmlPHOEO/9AbI5YH5qDZlRVtfvip4GznBgAHvHEZabzAGGoJ2ydG1L80+VsjXTl2iypjVQUdcoD0ZopC7oiUMGKtPnbQ/ER4y/0uM4r8L8jg==,iv:ZtlNuC6DylOwiQ9JwZxGvZ3EXxD9QXjdzt3IAZMHqes=,tag:gbRUyEmUMNabgYwaChMlWA==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: infra
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaelU2eVFQSHZPTjBvd3Nv
            c1EvUXhSL01PUHZTcDFFL01qTDAvdXN6T2pjCnZSRVlTVHBOT1BiNjNtNmhNZ3RU
            NjVFRkRZOXQrQkRpOUkwM3lqVml4TFkKLS0tIC9kYWdJRUQ0eVZ6L2tHbnY0b3V1
            aG52cFlBRHo5dktoMVhnY1FzN3pTZjAKY0vegKPfpbj3MkBAcPDQUG85q6/51sAB
            FlZLWV7tEZHhrijfyY0MkdznFTRAcPpX9ypUw2f72j9d+WJE+GrXDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T18:44:16Z"
    mac: ENC[AES256_GCM,data:cod6/wzbESRDVvqmdP9QAtTlF7WzRq6C2bmy48TaVBrVCsou2Q+hVdCU8mRN2GiX8JrGx9lRyWDA7asdxKOP0161XzXUyQzKqWSTXm7Lw+bjKZAR+OmgP2xlafFDWUbw+qoqbEvvaXm5pps3GOa1PyEVY5g2UVOLGWMDVVVEMBM=,iv:gNdtP2DI2A+y7xIeZjMWZ5ozkAK+serJebm16zi5O5E=,tag:Jqhky43apR/qxBPby7lWNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
