apiVersion: v1
data:
    console-password: ENC[AES256_GCM,data:5qcC/nOwlGX0/IvO/iC+Nw==,iv:bQI7C4hMV/c4fj4H8EEv7YdeBBKqHFP7cTcFEGQoYZI=,tag:XEJcNeIK4QCiSPSWaRgRrg==,type:str]
    console-user: ENC[AES256_GCM,data:i/WlnqlghjZzP7ya+LMyDgbwkuQ=,iv:bK4jVS3Q0tKfWYf8eNwY9Ls9D9U0wbmguw0GiSXcr5M=,tag:u5x4ofskGpkKYz+1PPmhzA==,type:str]
    db-password: ENC[AES256_GCM,data:ik8Whmy8lbI4cnpkU7uEU9tu+M9Dwj4R,iv:zZW+E0X94qXugeRPhi7bFAPtWs1Dr/9k8iAwx9SoaY4=,tag:SFGesjOgj6svHfV3AHtfUg==,type:str]
    db-url: ENC[AES256_GCM,data:vxB2a83P+OVfQsmCzUcUcwBB5SPnWOIJ2lwT069F1n8++0Pmdk81aXnF7m8CcP/w8cUd1RHqbxY=,iv:lJu9dQVVIokuvgRsTw2yTPdjUzDCJNnQ0F9BUo/QATc=,tag:rHe1JR2vqYAC26jbhxXuJQ==,type:str]
    db-user: ENC[AES256_GCM,data:lHfFjRtSsHD1wINI,iv:/+OO3T1TnIK6addNCKxA+kps3/KW8YRJYl7ZlTEOg/4=,tag:j79KBCYbBDSDMO04p5lHmg==,type:str]
kind: Secret
metadata:
    name: keycloak
    namespace: dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WnZrMFpxVXNnamN5bUFz
            UlBvU3J3a05icGVLdXRIZHNoQmgrNTVNOUhRCkppd1R6SGFoOW5oNEVZNVRNTHA2
            c25GcXFTVURCR0RuRFRRRSt4V1BrQnMKLS0tIHNDMDdrZ2ZDenFsc0I5SU1rMTFJ
            YWh6U2tqaFVDVmhzRFBGSUN0eW44cncKaijBXNLTgaGmcMjcypp+tIzhuYQtPPzB
            W09q08+xQUfDWLLoFSkYhJMb9aHqvteBVmnjsSnb4Ja9vSBbrpSUwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiamgrTnNNSzZic0VMajJo
            SmJtVjk0aWZjc04zU2k5dW9PVEVXTWdnenpnCm1weWtzelh2bGlNeGlSYVJYcFZK
            S05Wd0NjMnkzc0ZJWTdIL3R1U1lRZFEKLS0tIDdodkJlWUJqUCtDVTVObS91N1lG
            eTYvUTRZbXdBSGJQeXZPd2FBbi84Y00KGeAW0FZ3MQn+cIrUzmM40d8qUHox4w+L
            HYGB7adIRu0uQcsZ/tNl/VZ/8iT9/T2/XI1DTHguSQFXYFSEm8mA8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:12Z"
    mac: ENC[AES256_GCM,data:bSgI/SZUP02RhmSc3Euq2oXGWF245YRrl8OxGbK2u2EcN298FXz8CiiOyAdUYb6M50Y2g1H6ZDi7AxNTCo1VkWJUyFZUbeWGwoNocDF/x4lHkqxJKdhLWCzdHYBgpbqUc4kTpWKAQcNdbqbViq+WLKeib3rzKOtTTyj8kgi7Yl0=,iv:dC1aK1jLNxrNEVVZpw8siNi6hsL6LPyfawr1btEZFLc=,tag:pLfMkIHfj733gB0rALXoEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
