apiVersion: v1
data:
    console-password: ENC[AES256_GCM,data:14VgYetEl78fU3aEdkNHNw==,iv:AYACnrhJmFXs3ZXykoFsGglfP01fqK1Ou3wqahZyeag=,tag:GjXD6/z2RhxyXgJ/z7sygw==,type:str]
    console-user: ENC[AES256_GCM,data:2A+1MYLqDgM6kWtf6WrZLwLiarA=,iv:ej8KeDaf7Tl+7OUbBG5VcKo6uycoyT8+7w583ea8LM8=,tag:TE+Lg/7guEzjqresIHEmGw==,type:str]
    db-password: ENC[AES256_GCM,data:5kt8pCG1r8AK6zxSyr4EUw==,iv:BRhDBIUr6gLT9PtkwXS80DwGrRj22xc2nHj26bTX1Js=,tag:iRQubrPqAsQMpK0y7dkvIQ==,type:str]
    db-url: ENC[AES256_GCM,data:oY4xXCObOqmiVYr9XxQplklOXt4vsQQk5Uivkh/cZOfmF17NO1V9c4J+rG3kgLQK0uSs4/su/7g0yzP87L0/YEQMdoInDGIut8pf9GTpgMVo+hmO9xcs5hjY1BVFkMp8RV2r3wingDbAIbtBlMKpzkfy+pz2QBUd,iv:n6igiHw5+gAkQ1oG9aoqedP3lbL9fgqaa2/ZNkQps7A=,tag:YlnVXR/5odYKiJCD8GvHTg==,type:str]
    db-user: ENC[AES256_GCM,data:8rNgo/tvGR6bYwlM,iv:3zCHVJE8uTQXKvAEb0xXcKf3X6Zt85zob+JVaFqgANI=,tag:sUEwsPeDXM/UfHfPvZ/mng==,type:str]
kind: Secret
metadata:
    name: keycloak
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVnowZG5vTmJQQUhIRVJI
            WkxaVlVCb1BTeVJHdWcxVXJ1QVExdTVHS1NFCklLN0tESTNFTTBHbUZXN0F3bVlk
            Wm5uMmcrMHZUa2srNmM0UVVtWGtiaGcKLS0tIFYvYTdBT0RQSE1PMHNIekdWOSt3
            eUNmTytvVk9hemdqZDJXQWh6OFk3TG8Ke7T1oCXdqR4Q0ctS52E3kr9pDt4eMU7j
            Xf7I5gD/G6tbm9Cght79kUdk8o2J88oNP+SYxhLn0haWDekLwtX9ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T22:31:25Z"
    mac: ENC[AES256_GCM,data:gydQWmRCgXfDa0sAmG5PopWsyzFVT51YWj+vI/5zFaUC9X62ZnXGtDet237xZmNuVJ4AwPNJ7/ZVd4Ebd4Ofr2nbDwaOpMDK1bO3OYcSZVaynKxWyfRkwwkbRVJEsIhJeyU6umatdxIjYeklv6TI/TdObKIlqDg1OlnSel7j4gw=,iv:WIevCrAnp4kWN/QDVQSagp92YCJbKVb5r3OjwPF9Nnc=,tag:K+wGkHM5rWht7kEPwOmtWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
