apiVersion: v1
data:
    db: ENC[AES256_GCM,data:LDSBsXteGdDcvSsT,iv:Ud1ECx4WLrMD/cuRsh1O4J7/30OdAk3fkwd33Rd0cFA=,tag:uC4QpASyuZIUugl6GPVNeg==,type:str]
    extra-dbs: ENC[AES256_GCM,data:HgqH3LAMz9F0f2qd+QF1kR+H+miWKb6AtIWrHfmwnvh8rvb6HEoJylOyIg2VhsKczYJnz+kGFUTwnOk0MFPUXmr2nThjQLfhj9JkXg==,iv:f470BN59ADYBw2SQYnxIbT5rK8UXpnGUyGzecR+HwIo=,tag:CuncGo4Ab0WqRTtehC5atQ==,type:str]
    password: ENC[AES256_GCM,data:tXgWRMkqk+GJLwsWZwIt2w==,iv:dIRSHWtIvj4/kxE+vtbdzW0MfcUC3qm+xphLZmrMpRc=,tag:NfGQsbRESgYrHK89XiKIvg==,type:str]
    user: ENC[AES256_GCM,data:Eh64ehTIQ2Wl8AHd,iv:6U9vgZdMo1MkYaejzvXl5wne7AbbK3GkqDAgvEovDXM=,tag:UaJrKGigSF0HvAnnfJFFng==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZlJpL2FVc1JURUc5eDFq
            WFRid0FrRllMYUI5eUdyTFFBMU4vM0wzbXlvCmU5TitDaUFGeTVCb0N2cjJ0bThD
            MnNyclAxcXJEcUR4aktIVTl5Z0VUUUkKLS0tIG5XKytXVzQwNytDRGhSN0ZMQUN1
            VTNjSGUwR3hYM3BPWE9hL3hwNnFtb1EKV0QvlqbEK660NtSH6TbKEITQ6ituF4lI
            HKfNtSlBB76MhBfd7iM+pRPkMuOSa3e3Ob0oOAFG2mVP5owuLCua5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPanlja2VtL1ZwK1VIVm5o
            MjNzTzVvZTBzQ3BBSDN0dndWNGRzVFVQUHdZCndmb2JlcDBsLzZ1dDZrZnUrTytp
            QnEyNlZWMTYyamhETzNGcXpZSVdJdDAKLS0tIGxldlRGQnBjekR5WklnS3dPZjlX
            L0VTUzlTSE1CZklxRGw1dGdjMmp1WVUK0udPV95gU0F7zgWJaPepPvV+Bpnz39Eq
            ub45goVtlzGKOutaK3Js/vDVWDiRyGwjw0SuC1s0CWCjtodlTCgxvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:12Z"
    mac: ENC[AES256_GCM,data:ADgz0HMyOzpisMj9whutr8jHgHhtJE5e0GpkbkyZehyUvRYwRgKg8dsCjbjB1HhsCz3E2u53/1hGD7FYr4DCmsdkCXr/tI5VOQXs/dUErehDBvY5OXvSsjDqIJ6v/avIgomEG5DrgKp6AUta9ogxGR0cDECTvwMMYHLgMQ4V7NA=,iv:XR3IhalE9+jHTdrnxFXRj4v9gNRwiGSAReeNjSJQisk=,tag:jCLUi5/vCuryjwFdkiQVHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
