apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:UBkSukovMtTS/6gqhCNyFEbTuCvJqYSMZSvQPLyL9HA=,iv:WYgIbEJQOCI6v9fEcbz8BWqEyl9OtG/FQWk8BvJbELc=,tag:xyEgewB3FeYBMDvXhGp7rg==,type:str]
    join.key: ENC[AES256_GCM,data:rhwA8n1qICHz7k5D/AftvIsQejZ3OGeD0IvgsTSG8uHbYQk5yTFE1drXssUbsYIm5FnjpkcE82i8P3Qz/vhKsdyPF6JydiqeELhK87d7eWjcDwVbfdVWkw==,iv:E//VI2Msuy5XFwhR9GX3qIdtn49WXzztFrWrn65zeB0=,tag:6nHQf9g0uRN2XDnMKRShMw==,type:str]
    master.key: ENC[AES256_GCM,data:X3fGhQGK9lrAvnuf5mdHK94IpYGPfx9xLBO8tIE2FcijH9L8pqQn0y5xlbFDGomz/oZ60rBdAlF88hv2IVC5duzWQ7lAEhrfLTB9B1XqIWAdyNUV+aza8g==,iv:/rf6qKYooAGDKCHIn+r7ioMZvqhKnMCs6GnOIF7uRAU=,tag:r3Lpkly2Au8rMBODoyxteA==,type:str]
    password: ENC[AES256_GCM,data:4RQA/9GW4YEpjAtT,iv:0woeFQBl7wPfQ6n3P98NNAIEtwb/49uYqiifgLwBGnA=,tag:wTN649lGug6iFORAjQKsKQ==,type:str]
    system.yaml: ENC[AES256_GCM,data:CHx9rAd2qLkcwXf41W4xxlVxzHujKtDKKKXRjhurWUfyc9ciysKd8qUip56uOUYVl6iGlAxRp3oPJOErprESNgtSk8F0jqKMenXY/AB3puXvomIAlRNZP2dpAYynec0Vz3bjpdsw1W2SGhXtt2XhrRnmDuXbOoZMlzTxALaTIVbgipaepIbC/eeNPMYgdtPWW2284FxcNp49nxvEOXe9rP5YrO9rqCK/9dVsiIgEZcRYXSHMagR0kWd9HsmYoy0yv59hg7ep/BFpI3pUS2HSlXG/e4VNwA7/CV07qc53Qv2l8HozgbJJNGPOUqLxPAKAvVYAKt7YiIeGvV1BVvE8PLJOrIK5rdT9HAtMaAQnA9QCZmdy+f2dKcyhdLsT9mRlOIEgrmSna0L2IPX4BktGAF6mu5UlEVOf3ja5TsMiS6DtxQEBkHVLdZjA5/6loh64y/7Kbk4RW+lBe58XbK0XEEhULzMMFWrChYpWmKYm2rSd3CkhsOr97im4C1dI4KNLzc1iW9aWJOLBH5gZPKLoYba0pS+8vZnvkWlliMF+/hk=,iv:4V+1hr7vvPNqdqG6UbSq/rJ72qfC7g59CNtZ7aMhp8U=,tag:LmNzA8v1gVR6GssqOqYBkA==,type:str]
    user: ENC[AES256_GCM,data:cB+S2NAduV8ajCZZ6s9NVg==,iv:CHaHwZ1kIDGTOIzk0AEYzcZp97SbM3UF8S19jxTcMXY=,tag:SZxXZyy7PpklDC452POnBg==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudXVKN1JDZFdQMzdNSXBu
            VVRtbkFDY2ltckZIVVlVUTRPUGRGWUY3dXhZCm1xVXJEVTlreTM5NUdVV2xTenRl
            bjd1NnUwSDBCSTFBV0xwNHlNVVJ3Wk0KLS0tIGdYZTNzSmdyV284M1F0eVdTdXBW
            aUJFck9xK09wZ0xMNGNrbW91WnJlYXMKbnePhL42GlGiMC3W3KK80LJGce99U1Hh
            IKlcE4oGkpOl35zqb7Gzzv1SpdW0BJNjXR8uCQf7rPe9yWcR49IFLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T00:53:23Z"
    mac: ENC[AES256_GCM,data:NRfId7g1kF51DVhlpAW28b89plDu79y1uIjrfQnjk2nlZs83io6b7xtg3ROUtZnoK0YKBfS6/jwLyMn1/XAo3y2oIPmglcxcuRv5EloiwhelPttGZFcULablPS7A5wQnBE8dNn0qrHvYh/APiSGay58kvjQhirxnRk+/bJxRuc0=,iv:D7Xs8JQmZI61fzIB5vxIpylpC4xFGyEQE2cJ4lYrScs=,tag:GWok4AATqxVNaJThXP3eLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
