apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:DmdXMaipYxJeSlHG6N3h5W3k98/pb99v2nBB6MDlUl8=,iv:ESO6Tn4hBRgLGISnfbU4BE720h5RRSyAOzajl0r5mRo=,tag:OWDR1DQYnsuvRCxPFUfYFQ==,type:str]
    join.key: ENC[AES256_GCM,data:2LWLfloeFP5YsSE4r4nonklU++xO1ETXsz1lad51dILlxKJXrWRq1EaT8Am/1KGWYIoxIKJiIoQWdGkCgozYTUOC7MmEXbqwdpq3/qCBMRcS3LZs++iTWA==,iv:S3VhKV072m2W/BCvuGULvqmAGMy0YofMYZUJAABOKD4=,tag:1vdsq1vc67tzvqrzTd4IFQ==,type:str]
    master.key: ENC[AES256_GCM,data:2YTS2dGWO8UYF+86fMu+W7BytUsMINZ4NROrw+aPm2OHngDSI4gfUe88/D0dHdsFhwVODP3beDIX/HVFx96ijlgZkrnKFV8NF1AdSE+/hCAA28AqWveNyQ==,iv:dHaum7Tdd+vGCAdr4EyTRP/ynqASGjiXPtVErp+g6sM=,tag:1zIdRXobW3U/DLZm1tTF4Q==,type:str]
    password: ENC[AES256_GCM,data:i7jkutASHCe41cM7,iv:caVsdlJdOJK0E4fQuHPmOHwezWEnhRjIrPtvjpTqqEs=,tag:wgD6mNcFO8RufJo8pU0gmQ==,type:str]
    system.yaml: ENC[AES256_GCM,data:uS6AxRCATswOx11LCkMvDlVxHB0SqNMjmtZswYzzBjvGVeMTT34szXmAbAcKVssc04XBQl67neoktmAjETTMFyuQOlC1WwxZE7dA6Adi5hVEpKdf17GhETlpMmj1LaAuPUEuUSUHNc146zj3Zl9Yyj/EgG/SlM4qXv9f6yMUMwXghbdCSH0PoxWLJmSF53o7cHtDm1lCAVXGfp8BFhmzO4qcBTNcLLOabeo4aiQWfvGk7plabVJofpfTkxT5Dhsr9yf2zdtHhVDEjaQj1dLLET4phQE+1ay1XLZhK2WskktHAeKXqm+kOsZS7fD5OsmRylAqX+6QTWXtk5erVzXuMLNRVOZrivab8PtANP/nyQ7/Vx9JdKgU5KQ0fPHt8FljH9uAhR1BqnHtvo7v3lQylTAgPn34CSjJPFEMax75UhFlZXXNVlJvmGVY3jGXtkYpNBeUHrWNcdMvDICbu0Rkkq/tJnEQbP0EqIbRH3AYbrkgjJ29hbr7VppKJ9065w224WHM6NvIBdIZBHzM7p+dsjIPhY0JhwbGvLav72GcgA4=,iv:Mr9J1qZ/6cpRDmLo9MPijk+l7udzHlxa7xbTc4A1gDk=,tag:XYw1EbuoXNdlK172j5ieaA==,type:str]
    user: ENC[AES256_GCM,data:Vjp333oDEcLqcY3y3tO9+A==,iv:kkZQ3d2JtsZqfP0BiqQPX3CBfGWggpLDqyqz9+OE0mo=,tag:RPcNdjT074phmIZAYDbN5Q==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2STZFNFRqOW9DU0hMaGNX
            eGZwODNSZzFRSUFnL1UydFJ4MVBPbzNLb3gwCjZ6QzNKSmNObHVrZGxSVmxuVXFO
            NEtFYTVPWGJ1RUtNZnU2emdvdWxIWUUKLS0tIDhDa3orN3AvenpBU1Y3Y2tvU2lG
            a3hXc1dIa0dtbkRiVTFocVFqYWZyTEEKsVZ56S1KkoTBz1UCW6QPawX6rsrPhQfO
            0F72cJ7s9r5tg6FEAOeNFUL/rRRuIdLbfeX/yyoZYNpljQO8jbfRBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T17:37:52Z"
    mac: ENC[AES256_GCM,data:aQ/ScO4qjWz5Uirx0zbnqzeudxKCHQjOCf2AgucvyCNN0Gl0GOuxMlAEHWBdqZ8X194F7QZ3M3Xj3Zj3caCMTZ2RWk4Tem0tHF36ST0F8qvqlzoxlQhv4t4OHofg33veQ9lZy1HElo4J0M1f9MbrlCD11U2VZDrtLfR9e0A3RaU=,iv:nkf7BoBjOVND4D5rbTPBBOlBSCDYv1uPdeK3ElxH8Dw=,tag:bQHppWEa1G8URPMyFN49yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
