apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:qXs1xgEjzQ4XbBkpYxQcnNmrCwOTMFhrmlA6s3CSaBg=,iv:9D63xvSiK0pSzzBBPQkIOm+CxRfw47nnI+DFPfEapIw=,tag:+PBw8VfTMzgEEFhUjZBPNA==,type:str]
    join.key: ENC[AES256_GCM,data:H8Z3zHexIoB48TyhsRa7I6TMYRa3HqynCBH8uf9wQ3RYuwXA1EFoxYE5JFPbUrF0qGv+Lv5N/i1Urpac/QxMlLWaaErpnHDGDu5G7479RspdYUx9RQC7MA==,iv:dR5tHrfX+6+yoTsF4IK1SzLC4c2eOF2Nl+KvshDsifY=,tag:HwKkt4+1ukczxMqssynyEA==,type:str]
    master.key: ENC[AES256_GCM,data:nUzig2FoYZ/F8/bxS7w9T0hFhNoY6jsPFRhqOixlYOZX9Qj9M78raZ38//rCONQR9dL3RV8DiMBdO9mzn0iHMuN3GUwVkG6y7Tic8anWtCOb03fob8wr1g==,iv:SHMspCCpABC04aocJQkpY/rSE/USeeP4RVGfgx+CywU=,tag:vUL7ly9C7RvhdzJku7e0+Q==,type:str]
    password: ENC[AES256_GCM,data:POZb1rMU1csOqhtP,iv:/6LgTOO5+VaqO2Fso4LV+ribSL1hl1xen/+yfnXm/MM=,tag:eFHN5VHkUe0aHXRIsMmLCA==,type:str]
    system.yaml: ENC[AES256_GCM,data:nlQy7YbmlQx6bbkSQvBpC82op+Te6fv1XzRZjMd6pNDK14kX5514VDv9vIXkXMk48qYh9BN0VHK95H70MNIeh2V9OZDV5GbW0n76fDAXZaeVPNLed4CNIqr9trS54yA1jMZWSedUGmrIHIk/PoaojUQ4F3ww/lyQdHwF/UqMxqNUQLaLiqvAqVEhtNzgWJrm2K+3F2J78nfBciegb/z4WGktG5SmcVrKPyFgo7L9BF78U7TCN89iOWy7gTVg5cVTAq18HQZr5SmjLWLWitoP7SYYVq23djsXKeFODh28lF4rHgRvU4TUHHrvui+BHIHxoovrOETmlDnrNfQn/PlVZVyBULJitAn4OOQwFIsRL5YqoxT6kCsIsKBfW+mcfIBFPlPwxh0SXjKYqQQjoQrGM313j4QbnSz19v3JD48g9Bj9f/cFlsHR454YDz7xoCpMviIhSCd5Z+7jsjm15DNbNamE96d7Rll2CeFu2gJbue4GIiq2F5j8vebz8zO23xHzIpykLhvFUsrnCYxtMRWk/tRUOj2GuNf1Io31eGrvPMb+xZcD1dVFOZflTAGMc2gG3oWuZzqmVFL65aWnp3WN/34Yrs4x8CgL0OD+AAFW5QIp9hUbERmzAA==,iv:eGCHegSUOBk0teSL5LXcDNvREJKGQ1GhJGGnhu08b9M=,tag:Uk0np6Y5Y/KUSfBJaFYtgw==,type:str]
    user: ENC[AES256_GCM,data:ngqAopojaFUMKuoQD5edog==,iv:IuZ80p4TZEJUlspoZZWxEADnpj0LRkp7GJYs8QQlyxE=,tag:xBu+l2bkCLyyOJEt8+gHnA==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y0d3TTNZYlAzZHMwTmNP
            bTYyY2k3SXM1VVZ2TmYrZmhLWUlDYkRzWmhNCkdVcTYreHVDMXZ0dW1hTkxBdVVr
            TkVSVEJzOGU1OWswS3ZLQzlGMUpEVGcKLS0tIDQrTlBSenFHcE9NVW83K0srNGNy
            TFo5UjZqcGEvbStNN0Z4bVRCVFF0aWsKgvyCZLrh/fq1XWFHHUbKtUK4nm6GEZde
            0kWslcSzRpY4ZmdB/H2YUkzpYPdKg5Tfhyiwa7aoFt1yffmK8QLqlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:31:40Z"
    mac: ENC[AES256_GCM,data:QHu0qMKRxOpeEyt89x1WS0zzociU0DYTA49+1R8MAslpOL04+WiwJStbOUptVmk9sctQt17gop8bzKrrCGYcC0fZiOLudqc3Sjcm81WWD7joCnfpMkYN9e91hwS6XzK6qlEJgOyyV3b2Yh0SoIJJeCmGcL2sD5ZJ4zH9iJQyoE0=,iv:d8Pw8nSdSvz1fNW9eGmoO/k/9oU8+vFfDY6nGE9lED4=,tag:G542RKp3aZhfYWiWbpunng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
