apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:L+1vnfEVSAn5jNiBKC5LHugq8ZgaLoBd5l3+ne70UGk=,iv:QxzH9x0JOHBJgw+K4cVEz4NrVPKPEx/P/F2UeVpXbWo=,tag:yYICZZ2phO0r2jeDG6r6zg==,type:str]
    join.key: ENC[AES256_GCM,data:Jz5xKlj7alP/qEkiDd0qs+qIYRdviy07xa73087oRRAG9ldUN0DlhX1ASLY5J99Xxe6P8itY8xYONqMH6CrUwWyitsuzJEp12CCSqBrJcHPSsgPtt8CbBg==,iv:157VX+bfks77nW/1E7CkPKwVWOq8+8L7u+VYbu/0Rjs=,tag:UQhQ8ItiUFMoSc25RiQ3ZA==,type:str]
    master.key: ENC[AES256_GCM,data:wKogxq/4R6lcgTc8yZOIxoHpdpVy+xVfCg0J7/tvZj/VtWRfxoBYsXVMFPMhmM8HZFgLE6EiPZojYmlzt88BKbe0TPj6Md+Blm11+pJXC2FS/SBKLHsfDw==,iv:ITLop0VHy77YHd4IyDr8MUZQ+vMBQiRYWlkoez5ipls=,tag:oZErW/TtbmkM7Rv0XRdUbQ==,type:str]
    password: ENC[AES256_GCM,data:wil++KWXW5Kyjj24,iv:U8Dhw5WYx89pG9GMUBN1WEUD/FgkgNuUlDBtcQ5tnDs=,tag:/lv4zQyg+kc6V57vFkLrjg==,type:str]
    system.yaml: ENC[AES256_GCM,data:y38xZ0Xy24khTb7jkpxNEmeZ7eeF1TFqZWwL/taeLxdbIcchgI/MDHGN5HeqmqHWE6ouv1kxuG+pocsMR8btq+707Apx3sGWWsJlCRm51zcY/qzAdN2kASHgp5IDnfnCE9Rrk4doKPdP86mGY0DB8ibgdddTa5gXNlOdosAgtICRICWqJvmjgGTyCHies8lkQvTNZF6wflMzsGZdyawUARZZfynmDW9MCN43n1b7CB+CjP714wZuMTE4BktTJRx3g7JwfgqOamLgpf22a5AskEVrGUuUu/aQ208zhZjrlRXHT9+x21RxKNXXrwT1VV+dpwaqi0tuXLOyxNz2ClFmuPz9SIMk1t7sPJ5cMfJucj/g6/s4UheTsuJwyOTGyAAaA6MCtcwElTolMggOFESQd8Kw367lfIlejb2HpCgox/Mg7XFQUoTbH77tEX7tQi08nOa+SwaJ+a5QOwpy3+cGWaRz5twKwr4X/dTgLbuTepYScsCwWxDLNiNac+K6r3xvB265+n1wGwRi4xuN0X/EK1lxU7OdieDkBeTJLRGn+0oh1Jjy/8PPnVIQ6zrjLPPXEhuG9V3Y6I9zKm8Bwnh3pRZOJu8XFMzDcBw8PcW0cc3uYJ5MPribOw==,iv:F7Ai8EduggXpm57SgO8/YKk70nTcqKkfrYyptInb6Jw=,tag:9mYD7mFk4CJySDw7ktFjRA==,type:str]
    user: ENC[AES256_GCM,data:kHp1WnPc9LLwhpo/lHAzRg==,iv:846QWS2TVLBlVsXYMo+ooJqyadkGvq6ZPXbL1A11wd4=,tag:Nxu8mfzWOZ7VKGkLdxI93w==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdW1kcS9JaGE2alYrY3dH
            THd1SExXOTJ3KzNER2RTUEtlbkZIdE5UWm44CklQTUl4dW1xSGlvS1hISHJiTUVv
            ZW16TEhoNE9lWStYM2xmazlhbTBFK00KLS0tIFJ3L3QzalBiT096WVVpZGZQSWds
            Z05pU2JiSlNEMmtuK25ROTFRUFlDNlUKLYh64F+HifTvQtaeTQKy1N6KOY628ZAb
            ViFMvOlPyJjS9aEBFDuEZZN09N/ZG2PRm8lVUsT5QQC3E//9wx1AAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:31:56Z"
    mac: ENC[AES256_GCM,data:sNkUdvs+TbkXuvHfQI1dgUGXC7LeKF2gbNyvEqVxHEYpJew/XfB+QHY9wVkO/UNOafOZy3W4SUNTjGV+jdu7ENMf2Fj6cCVeUYxbgTF2zciHAIZAbE+IxlP4DNeKiZAlgRY84xnNNIpKNlXeqyV12ZSIAQkq1LsTlFMCJ0IM0IA=,iv:8CQi5eXfZiXE4xuTbuBWH6OoPR894HmurcuYzZiyFd4=,tag:VU5aUqtRp4WOMC1ElR6S8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
