apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:B+j3aPV10oKWcgOZqy0kiR+d5rTAgPnycmiVz+QDe08Vxzx0P6uGuLrpVgPqYwypFnEJ5mr3wBNSxp3a8Jwyy+dVouA/yo1Z7X2FLxUaglW693RQ8UnSjesZN3OdFAAD76yfoLddeKc/XTGaB9l8ssG9axYuUefqD9FQyP1tPA5glsju2T4u2y+OR5Rdg4TuiZsoY3U32S6PwLc9EER/+8sgR8IoW1XGDRGdWHJEkw2dlTgqUAzwT6iFaRnT6cQ6zowsiFBiObEkO/cKtmR8i/mt5V9OqwU42NgqILPUkytvZ5FL+mYypB/YgwHBz1niahsGs5M/MuSGvqhVBzGEi+MS78hxmbTR5zwjgVx1fAtnZ8D5OXHABXQcOTO6wa+fMlVyQM3GzBLUtLk8GLPB8DSX2J5A7gAixceQFGMh+3T/rUV4jWDgYWa4oRp0V0T1L8TFMr85oZexMCpavvaO2Vh1Wwfhzb7gSW9YUVxTj4J/y2ho7x10P1rzObbWHkp2vf2R/a4Ebw8btMlE,iv:5F1Xq0vjdw6keFjJF+2TDswF3H03XtqqzOh0/LiAU5U=,tag:hoQIpr7HwtPzwdfpbR7vVg==,type:str]
    config.json: ENC[AES256_GCM,data:EX1uJKkO5u+Cc0VnjIcadU0TrcMXVYDuZqyRveEBuvnaH/+pRH+gyTinelcT6tsaAL5vgl3CkP34p+7MdA/kG+gNXX/RfbX1YAosU0xe1rKkv2kZWaa+QE71p7UitYuVzNoXjDk5jGKntDG41z9tL1Yf3o39RqEQZ/IV4tOZqnrMU2DKCdWeCXB5jG5SnrFYRtoNV1Ba1HH99KLTlyhevAKK01LfNvdZgoW+r/U5JXg5X2J+C6i0aRIy+EtS1xzjRrSZZVHTI9nbiCjTbkQcoN2eUkDqXn2pISJTC76BzLREIPD8aw4GJ3nc0VcjqheSP/BcEG2VCkzQf+DeLHxj8hKjatyHd9lnqmSqLpgkmIFWIucFNtRXy/vjFIkzeRZFh1LvHqA/r2XVRGZRqYGJ2ELZwYZ7dXRRYpi377z42c1OUDHOiPPOtO14/f3qBCS8QyHhSLn3nnfJmZ5CNyr842535v0h1lR8DhIGVhxPCDCwTJmdi6OT4cSFV6nuGEEAm1Q4T1wkST9n53qf,iv:VSRVSb2m94vygjhdg+vCH8Iwt0BdwR2ARvfNAzrmfyE=,tag:QJJqSsytrcuEzZSn1+HyJQ==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: infra
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQXdZYUo0OUVCTHlzc3dN
            OUdxd0NYcmoxTmVoOFp3TmY5Sk1MNnNROTBvCmhGYjRZVEFEakhkSWtMNVF5Z1Jy
            d0hFMFhPR0ZiRG5sQjM2Nzl2bXpzbnMKLS0tIDl6VFRYSzJDb0VyN21RWTFzdllr
            RjRMZlU4VGVQRTRLV1AvbS9TUHFCcncKmhhIF/xxPZeyRL9EqF66B2Aca7Srmkf/
            VNhCWZFkmsW8Yg2BQ2Y5bo/mYduUvNXY52ROnXPaubkbL9umIth0Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T17:49:25Z"
    mac: ENC[AES256_GCM,data:dUpjd8MvejjaPTKcRz3bFhfzQQ9W4xEhjSBS4biGwO8FdLmhS4ELiL0CfZ6uGuCNHPbj830Mp1VeRipqd/lXzNgPk2aDt4aYmfnjgFuN90VfhSEXGB+eKCZXroIcPyh0XXBlTZQJyJvHMyljRoA4xRZ1CIAFoqySH1XWP5ie1+s=,iv:CWGFZH4I29s/KZMQi/MF+zFBjNBYn3xPAyXqmegWCnk=,tag:o22mSy7whFfZGySbgYyOLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
