apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:oIVteA9IQRiVJYAevCfZCdGeZNuInYt5SZDFIy0cq9Tb+7TVGf9dj2FXCtPzOTdm/mGPzIYv6i/R/Nr0fE7jDthRzPm78t3a5z22lXN9uvT9wwu9cHgXnn05OZcqZQxaVb1lzPNPcjMJiTYVTONP95e958NRiNpqib7bJJ0s2aLO/BQbEEQKHdlpNDiZt146kx0EFbkP8SlctqS3Kmu+hx6/DmhL6ZWvoR6foD4bi5WzkSizQlPatzg3DdRT6uoJJbmNo4ay8m2t5XV66XrGMEfJAQDK41nRCwcP55cajnrGh7eNPhiw6ZSuRiEuCaP5sLSVlM/l7LA7vEDsUdoBhj9P9gGLeP3NqGGbmBDTIPDSjuCSnKDS0Q==,iv:l7zdLI+w3VG4KzBGI1s0CB+BwWGb/PDKdJVugFHhoBM=,tag:dFkEpOd4h4SZ2JZL2pJ9hQ==,type:str]
    config.json: ENC[AES256_GCM,data:fkf72Zzv8PFU/yGDbJ2DysspOGlVwnVS4Rf4LCQx1GFFX7ErpIt5XQLUb1BMbE8LGHjGXHHowD13OyN7Am+jQOl+XvJpZ9qtrsOTuR2ae3DMMkmXJy/8qc+wskYraB3i3M5DYbWEuUAcwx3Q4wILyDsEFOFzL6FhzL8aNdA25wxEyOF5zRHtJNCPWN2HQqPkFU45iDuP0ASW1bKkVLzXUv8+Shf8GP/t7ER6h9TOS7JmhnUTcELNnr95UhbkwyffBbTjznODaEWpoIy1JcZOyA1msFSbB5qAdQyOtjVSCbA8aoxL6jIAhDALUWLQs+XdMhDjfHLrhnADwqYPOJb5QMAkcDP/oEk3CZ88OnR8xDpyNkmE3CPR3A==,iv:mbG6qmVzMMAmdTjt6V3mfVmaiMS/0eS2mJGeG5y2ros=,tag:LWrr3uzw35vtRsgjTBe25Q==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: infra
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbGp4M1NoSXh4K1VsRGt2
            ZzlmSzR6N2RhdmlGdS9HRVA1RmFiZEx5UVRzCmRVK0N0N1k4ckNhVHVCcWlGQlky
            Y21hcy9EYzJ3djJJOUM4MnZ6czN2NmMKLS0tIE9yQ1RtZWNRTmxKM3NSc1ZGWmoy
            MllGRm9RMnRRNG9ENHpsczlEcVFIdDgKSkcWlHNFdUcfOm5kX8neO4A29nmt1m4o
            JNlmO0WcqgFd2WUYSg+aUXaidbau1cEkcxKEKD5Falt5Flnm/Jifxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:27:19Z"
    mac: ENC[AES256_GCM,data:upDewxsgZ3Wo2keIoYhyN42wDnln9hw9IP8j0mkwcIBPA3XHStW/IBjLVRC1hEVSyFaOEhTW10O6fK2qKOYsTL2jrhrzSS5ZoZhXKSOqHZimdsqgJNAsIedPZWc3RZraJ+PFgXSsMXo7STbMpDTJWXeGC0g9zMPddEAdYchQg6w=,iv:Ilf84HThrEruIOABKlwe8f6VMBdv5cUjvkrvAtVIyFE=,tag:MQP0IUcwDX/fOaHjqU8yiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
