apiVersion: v1
data:
    console-password: ENC[AES256_GCM,data:P5n2eZ4o0l+kHQNL,iv:kUG7yMWzEOTm7V3MdTCa8mnyCBHGIGptJqkcNf3VbfM=,tag:MVREp9+AxeiFfWkOV8HMFg==,type:str]
    console-user: ENC[AES256_GCM,data:R7B/wfAde2itSLZ7,iv:id6f7KwsLbRz7+qQT1qmeouhRFc6i2HVvS/ypGNeJio=,tag:olT6I8p/PZKs91wOD9eQLA==,type:str]
    db-password: ENC[AES256_GCM,data:k1bNpMAqG9By6FGe,iv:6+zkMATBoO+dMMYbrVwpLR1wpD3pnSX/BcFiEeyZJrY=,tag:sx3olrGObFKvMGRoXseXyw==,type:str]
    db-url: ENC[AES256_GCM,data:yHQyWUdSM+Wj3xhdHW4Ue3AmNqTXNhxPgbpG0Y6jS5DaquOjelasNBsnkY0yYKBkPT/FMDBuYXU=,iv:n400XnD8/pJwaJdXRe8v5u3M5DJrncHoQ5Scy6lSp8w=,tag:CKleUzN8U1uSKKAljzAyFw==,type:str]
    db-user: ENC[AES256_GCM,data:KMSYKnVU64GZJOWl,iv:kOC10p50qNMFyPnl0V4B7YlDRdIsej+BvEtQeA1wUAg=,tag:Wis9EDRqyY2jp4c8PNGSQg==,type:str]
kind: Secret
metadata:
    name: keycloak
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSHFMOEFFS3Y1MS9mTGdi
            ZnkyamltZ2JwdUVvNWdoNHpsOGJuZ3VsWlZVCndPY1V0ajBnaTFwbG9IZC9xeUEr
            bzEzYlYrZnI1Q2FPRUpLUEVyeXlSMmMKLS0tIE5CejRuTXlDWjIyYmMvYXV6c2JO
            U2FIdWRvN01oNldTOXZYYi9KUkFLSHcK5jcqYsXOI4YkzArIgGS65wSuV1yEnLqy
            sMyuJVQHUZuWY7SYn3juudPADx9xfr7JFG8GCM1ngwMLSdkX0xDPAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T13:39:33Z"
    mac: ENC[AES256_GCM,data:7wXIqWHtzM/yedzFWEIZq//AIlxa7viyooUCzzDiz+MkFKGw4gH0YbSEmG6izX7AEoSgSCbPitorVC7ZBpppQWtJNgQv/P+aUASHsOotYWCgicMUDftST6wKX0gBOMN0672wQ5c57cn4jFjm5Zt0f3PSC+3Its7MiaD1RymruVQ=,iv:RYrbktWPpf6biSVuy26w828YeqtUcfldXsTVuuyf0LA=,tag:5Efe6FOn2q1oDkj3t4hMTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
