apiVersion: v1
data:
    console-password: ENC[AES256_GCM,data:gpoxw9/tCCTOCZ86,iv:zUz9k/qfs5VaHSNuQWhlwh9rufqUzh8f1UWEvx3yy9w=,tag:PxzGFkMAlS7To0qMBOA0gA==,type:str]
    console-user: ENC[AES256_GCM,data:wbiH0dch4aLXwFTx,iv:rmL4foxttCOCeDBPPTEAUX5+zTBy4SR6tSKH1jDK3fA=,tag:vV4U9qz/7dAJi0ZrcEssow==,type:str]
    db-password: ENC[AES256_GCM,data:sphh0VPDY8CD7BFS,iv:bWhnWhdP7gND1Ix+err2t85p8E+rPLinwwclYQ3JxdA=,tag:OtWEwEvhTI40b1nKnfatQQ==,type:str]
    db-url: ENC[AES256_GCM,data:XnQPHIhmnix+t54VnKVNJG/Id53eEOvpGwgUw/D89HDSNlXkgf7AxpkAS6xKiT3u3zLDCcxmuwI=,iv:/6qHeaaSHGFb/f/SByOcQzDiPBTiWCjSW7A7nxzGZKI=,tag:gdqdTVNerfU8bpusecY5EA==,type:str]
    db-user: ENC[AES256_GCM,data:XqD4UF3RHmA7HdI0,iv:l8y3xjU7vMIxpJvw+3Syaneny/I4YjFd4q1BZeLCWe4=,tag:pTy5lR4/zhTJGc1a8LNthg==,type:str]
kind: Secret
metadata:
    name: keycloak
    namespace: local
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdGczMllETmRYSE11OGly
            NEt2NU1nWUVxVnNHbENRSHBWemF5OFdyMVdjCllLVUswbFdzNnRueS84dUdnZFMw
            V0I1T2hYL1ZqaXIra0FzTTVzVnR2eFkKLS0tIEhNc2ZRUWEwTFJHV2djQ2JiWHpo
            QmlldjB4V2lWd1MyWjRQc3U5L04zMHMK5I1a+APpgyr0w1AnJmzK7U0ioYIN9oT8
            TuhcCji8gFEG+n9kTgWO8pGpuf6ItZM+kz4r05zI9ySv8rW0DddNww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVlFMRmxBNnZ4WFVKVHQw
            ZkY0MWt1TlFPYm9MWlFmenBmNy9IU2JMZTJRCjJKVzA1dnJlNm1IZ2x3K0hlTjdM
            WHF2WkR6Nmo3UEo2K3lrVEVXZUppQUUKLS0tIEtReHhxVWtCaktvTmRKVjlrckpH
            Y21Ddi80Vk4xM2sxYVEwVzlrR3RkSmMKQP3Yt4zcDuhavvotBw3yMBcrSvHT3DsF
            v6uUeUYT75NJARmKFGcAcmf5P+EUmummPK8tA/ac1O1JKWgyPyTcVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:10Z"
    mac: ENC[AES256_GCM,data:+/x/7JQk2OlOWfN87ZX/HQGkf4qihDuw5UmutDm8ywqkkE0wJhBusFv1ppQPOk5fHbuJIranCoYY+7/BWwyPPnqjz4kkCpaPq4m8I1qWqp551ULj2EHjDgg0h5YXU9SAyS9rbFTnyLsyTsE0+Kat5DtATWjCDszYjOUU2pPpaak=,iv:/9mj7YT3XUJ4IJPXSz8yN+RHqj+vBMqxWYnWvf3lmZQ=,tag:rNvDNiy+DSs+v5TK3ShKew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
