apiVersion: v1
data:
    db: ENC[AES256_GCM,data:W145oEbaigJlFEFf,iv:DJXhrp/cqkbxfr6jVkESmrG/+fAh8OfEekMZHKJd92w=,tag:lYsRlGZW5IFY3nDEHdMxww==,type:str]
    extra-dbs: ENC[AES256_GCM,data:s+14e1alLazvfvFTmznGHDvwpXGHMsUKQbZEpIsjBMGaxKrDDnT625sgP3evPgp+V73cIpafTnnR1AXmVVlrloSEKf4Cca1O/eV/xg==,iv:19m3xJMQYf1Rc9Z9dAoZhrgiwNTLxLO9ilfRYLd+ZW4=,tag:jYF5KKHUVhCjg4N5klnsAA==,type:str]
    password: ENC[AES256_GCM,data:AtOhszVFOasC5p6F,iv:u8i95F0ZozabE5e5qeX284NHc5e2zSbF81htKhzgAAA=,tag:qJvrDLWxvbNp9iw+b36HVA==,type:str]
    user: ENC[AES256_GCM,data:rRe7yKMyGICW/4+Q,iv:Bcg6WY7gLHT+OWPyft+FEGEWaz/1fYHtkKZzNOEHmUg=,tag:h4HxMgBAg0h8B/4Oo0tK1g==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUzhNZ2ZxeUpmNjRiZ1Fa
            RkQwdG5abDZkUTQ2bFk4ZU82cDVnRmZKOENnCmZRMHRJNHZlMXlENTlYU2pZTFJk
            Z0theElvaGgzRzFlUkp6djVaSXFtOTAKLS0tIEtKRnF4TU5GWUxrMERxVkdOV2pV
            czJ5QlVtV1BNQ0Vja0tiWEdlSjEwYVUKbObVsHiOCTURzIvWBz6qFV9tsC4PnYPZ
            LxX55rPK//jyAVcjpEXQuccEz6eeUNYC3oFdLS2hGRXbmBzvMxgiGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T13:39:44Z"
    mac: ENC[AES256_GCM,data:0Bjwtx46GED6d8JLCE1mri2iYNI3F0AVIJPBXNXgP7ZffTTq0pK0Iwd8Xsq1FJJVJdkoa1yIV3DXoXDG141tcZOCn1SQKE/BbdkV2RiUZhoIn47h2H8MsyZHcGR0yMNPveIee8+eP/Ex2aWPJa1vga6kFhBhXZyhloJhGqa98QI=,iv:Hu29h3nMXTqELyfuYabsRToY/AqUepu+rto9X04peao=,tag:HIZ0TKqajP0O2E9HhTzpWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
