apiVersion: v1
data:
    db: ENC[AES256_GCM,data:sijqUSwW1qF0dWgB,iv:JLEAk0KPdSltjV3F+ZhGstirRK0pCmQPbNGcMmhUDiI=,tag:W9bVKUWRv5YNBMkGkHpufQ==,type:str]
    extra-dbs: ENC[AES256_GCM,data:MTVYpyDxgabeMgiGo4YwrWSF+hKL9NXWFf0Gh+VwMTibZlwS8hdlV9TWeW4vs8k2ob2DYz/71DKHKjYufw3wA3PHvlAQCK4avuJwqg==,iv:E2LeEtwsFUVF9Lv55ZdpVomvMTzFPGdo/x+BNBE8e48=,tag:FXMiGE5S/EfmdNmlzS/0yg==,type:str]
    password: ENC[AES256_GCM,data:eEVZsgaxEbSulqC+,iv:55m/X0wHVkfvP5hQMIT9bGbctAT71w1AavP9VOlhw9k=,tag:9Ht0dk3mE2y2oqGB3p74lA==,type:str]
    user: ENC[AES256_GCM,data:uBI7x3+eZOLIms96,iv:/blAxSRyCsqSnYF00A33XOF69MxTmIHvl62u75racNY=,tag:DtVhtPxLrGiWzRnbbbbadg==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: local
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdWVjSzdxTkhNUXBydG5n
            anNSTUhvLzV1U3NNS2h5SlNIdHJBLzduSTF3CitlUmpwWEZjditwdmVteFJCS011
            WHBoa1pUYnNEQVZVa3V0QWpwRE1CMlkKLS0tIFRpaXRKcUFRU3kzZEplNERoa1lX
            Y2hvQk1BcUx4V2FReGZORG1HdnNSMEEKauR+h0rqMDad3iZ908hkcvjOPXCJY+aC
            +SxY11ZyR2CegF42aW1Lc9qT7nJzt2FpE/OFZrfvOKjgSta2XNVMDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUEdGSkZjaWF4bU1udUZD
            a0dmbHJGc3BVOHR6MDdCMmRRNmVHcW5zWDM4Ckt2ZXVGeUpkd09GK2ZHVTlQVHpG
            MXBuOXRHVUJFZEZYdHVYeEV0ajllSnMKLS0tIEd6UE9tdGpkOG8yVjZSVXFYWnNN
            alJDWFlLNnlUU1RkZGdkSFd1MkNyTVkKwF/E33uqNtVNpKAHT9gcC5u7JPpWj89L
            a6pcrAP7+tOqsplcaSW7no7nqHPWsbVQkK6tHUHUZcnZrUBK7OiLVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:11Z"
    mac: ENC[AES256_GCM,data:LVbgKyVpbC01theCvcCcwYbl9/VVVMvX+wowwuaSLWmX+L//g2jiCnJ5iBxW6lKeldoaSjmKvt0DTwAXkq5h7294ZXuuiLl+dER55nQWR7sM7TTqAsW6WowIAXzprFTAol+V1wWXHPIIMDx0L0FkqgVJm5/aOHiEAHF2/vX6ys0=,iv:5/e36rPkZthMprHgyQ/HOW1ck2YThvJYDIpqLGzzAzE=,tag:nJn2HwOeiOUwoUAMy0OnYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
