apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:7cEfkVIgJFWb4A9oSOQsDMae2Y9OKyHyqu7dq/fsM+k09S8n3pKk+h8HUgU=,iv:7inr92c3jf5I1d6TxIxT90RkRtPkAs7fZhiaMU2a23E=,tag:yauuTc6TuPVz02no0zsW8g==,type:str]
    join.key: ENC[AES256_GCM,data:Hw+8tXu0Lnt/OesDrSsUPlpTiddyLr4wgL2hTL+j32nGmrg6TWeB8//GhL1hSRwN/RRAtIdGV/69apjmIRjLZW9uEUSkPX8VhP3rrn0YDgAqc81XEiUv9A==,iv:MCMcQjrmXv3yuItbg81cu3CrdGoQk2EwKjwDWjLDbKo=,tag:/wj8KIBYZMwdXkA6Mij0Xg==,type:str]
    master.key: ENC[AES256_GCM,data:vvhQAuDg3e5AsMlUd0eDj459pxZzWwudkVE1Me3rnZ8OI/SQh63N7nriZphWuCrsLodhxk7duTqbUwAZwaw67tx2O9qCKonn+f0PfYv2vtJQ6PKJy2NpZA==,iv:dMiFbfasDgrDCqUea6gwr7EHeqIObsl3bc2rl+cX2kc=,tag:V3MiALLMdmtFRAv2XMqqlg==,type:str]
    password: ENC[AES256_GCM,data:rV6Q+CSqUiT7vPJQEKU2GtIkxhWT0IsgCZBeFw==,iv:5fsZ6UvfGovb8Jmkw/JksTLu1eZH5WQOh1zegVWC/ZI=,tag:B28bIp1CjipvlvXqqXtL8A==,type:str]
    system.yaml: ENC[AES256_GCM,data:Xh9HUswj4sKYxJBmltBQgwAruubKR3Bwuy2tEOrVcoqz/gpIT61KLTf5DGbqddfkiD+rM5atM2iB7jxxNrHnIRY/ytZrKcUeaubbcVlgifC8oP2e03W2vPJZjrKFKokuoDMnYZKAYlhb6iWln9RQJLCtFnbW3NPyXiM3WGdFZE0W4B2uTtN5qyqVUHOgnj/zx+T3Oqf/9HKjs5RczFZWxUp/Fqyz7qo4iX7bTLHPnPXwZ01vPCcYl7svih62xehGkeS0IXP5AtWsFxrkml3DCQ/3bPSmWeBJP4kVGwXuecFoaTyWAG5TepDVaVPEjppS6lZjqTqXynyhQlZc5mI3VTF9jXbJwzG4rXjSEzv05IlZTaRS4OhFLtnUwk5Ib04cfEsP70DONPbgFtuONlxl/1F3WLDHUalr3ICujnhOfDwmboSS3X63kE2BNu4V704k+1pF3zlsyKtw6EgnksZmXp0ixktPbKF/FnIDsN/Udklempykvb576wtdTKvJ3rPfmRD6inr2hCuMb1MAMvAt5rkbcugH5uAFDMKuCP+GjQBaTtxPF+wLLTElbetmn5gvTlCgQ8mKB1UF1ZfCqLv/Kesh62aiZJk2mT7CFmI3AVSz1zhf00gSOsQWGdtu9BHmzl6Esw==,iv:EHlfrRdev26VuYZZAn3/bdNNLi2lSBLy314tSJ1xlcs=,tag:v36XHSMz4/4XtlfA8wNBdQ==,type:str]
    user: ENC[AES256_GCM,data:DKIr8kG4puMKIhAyB9jBwQ==,iv:68D6MWhfxHBM4RimOujval73ENHsjn0phQKtGGzTnSs=,tag:R40MvL5si12ZdUPZzHOsSQ==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: int
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ2pqOC9IeTJoUkJRNUI4
            SWNBbzVrWjFYaUlaRDlSd2pzdXR6bWdWU2pvClh0ZkkrYjRFQTZTc0xYY2hmcjh5
            WVZoRFRmR3EreXlBd0JKZWV1bWFFZ1kKLS0tIDNWTWlpRGtEWTQ0cHFlbnBFRGpC
            aCt1VjhxZzEvNkU1SlZ4akdzRXJ2R2MK5fFh+qYlANBq66nzMlyytq0ymUo8mhB5
            sF+LUfPxAAzB9vNj48wYW5no5s81uJmPbx6nj6Ih5FGSrQrWL48bNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdStBUFJUTW5oaVhlMWxG
            OHFiNkllOWtmSmo2bnRkTzRCUzh3bTEvb1hRCkVjeEFzZk1RaEMycXRkOC9SYnVC
            cnpBZncyaEpwZldmZ3BuK3BwMkNuSHcKLS0tIENKMmFCSzkxS3dIWk9FSEIzRlFm
            alFTcExmb2RuMk1xdDBvSm8vWDVsOEkKTTa8IyWQAVYUMVrZKOpgS+HXwvJUkUyz
            6sfINdavMbubl/q+56PiJ3zWdE1UpmSD1grIte+6Es0HowSed0B3gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:11Z"
    mac: ENC[AES256_GCM,data:HBJn8Q6WPi64g/foAkbWz4SElppWX/Wa5d5F3DrbZNFGE/yNO5uUjG01hMSSgWGUnigud7AA7I8PQ2UaoaqxG4QBj1RRHOz7+w2kxgXYy0l/Y4i9t2eVzpp99T3qzV5+Ay3eitmdaWxQbKG1F0vXRo8cKR/wcefMRyA3MobEvE4=,iv:KqAFK5whwScyMySmPFEZQcdP9tmKPteNq7pZiUHRVMA=,tag:gVgRHXfRezxqTIN18UwScA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
