apiVersion: v1
data:
    join.key: ENC[AES256_GCM,data:+kP9qgnYbwe5tvGA69G0pdZZ+J64Q3skITZVYschwKukSCupq/3Ie57/yiH5GbJ3wiGB5qfUDCd7at98exuopAqCBmATI+wjGMlUXJ2qvqHqudgl4G8UuQ==,iv:6p+y1kgyXgEgWcZkM0xL0Z/P3RgXSvqYIybFtStOTLY=,tag:JUXdtzK3p9Dy5Fjpwhr+aA==,type:str]
    master.key: ENC[AES256_GCM,data:SZOM1CBmQS9R7HXfbew40r1PtcNBdqPS3URVH40foTG4PGAmV1Aky6RUVL6uHmw5tYmNivvI3mxbqNlQoOqbM7aO1x3ps+AQVQnfpOcEtmL0zsS3iyJ+iA==,iv:rmv23+5EntGsNWAFFkeSh6NZ8aKabGoNQ8GKL30keCI=,tag:f2alYQG0vEh8B737brNbDw==,type:str]
    system.yaml: ENC[AES256_GCM,data:VzyAH8R99LNoOyyKSDx4fr0vvVYT6aB4FBxxKyiouqbYSqP5iJ6wJ0Zcl+TxDbdx0VPwj2IurmrgaomDFtcczZ3yZbQa98v0WNYBE5aOCYsNJV/Ca4deRTtrHgBStMp1Yq6ICQEExBgqViynrOT28lpEQOV4DvnfAZCVxr5QbHJrAnCrL9tD81CzAnwM4sB2u+sUx56sGjh05f5opsI2BO5/5HP+ZJeZbX6V/AQBJTLoFnWpeFrGR3K9j39E+920ZNb1imaRxQiVsvVqJvbxsvX7KIp8Xnd+O8355KN2l78R9h15i0VkYTDkqsR6ar0iLZJRicdSI7w4B4T0QIZhnuYirXsahcxVXGTmaVSt3NR/ySrn8jcZl+Covd0U3N5Y/CzRkSkmzizs/lab38DRm8/NBVCpMjp4Cu+IAzTPd6yTIW6z+BO2ZEZrHDQOXslf6wrekheT4to9nnqPwjyPbNLfeb3g7aBX4Jv42nzPZwCAiOE8v/UhUnaN3JIZyLLqQnyO+fuUD7Wdcse4qPTmlzU8dlOzQiyywXXHh0RzEpvUbL+1DLbmPw==,iv:mcrS9gJkXNuXDaS/rNtV4Kwx1h0hYJUoUWmibKZWgI4=,tag:s6PwtylON4Iv7bvQDjvXTw==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcVZ6cUwvYm1BUndVMGFQ
            SnNsa2RrY3huRWhaVlp5Y2szWklGV1ZmQTBvCjd1WW1nd2NFZVpQWm4zMmVWakJo
            UlFuRFBrRlpFWjUwd2ZNdmFjY0lzUTQKLS0tIEs5VndHSzkvb3lYSFNDTlhjdUNU
            T1FEb2lYeHdzTEx6TnRaWVV3RDBaNzQK+x5WINEqeheOA/0WY6C9e9E2bHijZS+d
            vEALRFe8Nl31/dv4LKrp70540Dgi9PwF4okv4hwyBZntHmjx0Ruwow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T00:29:55Z"
    mac: ENC[AES256_GCM,data:AT+wS4xhsqt1kY1C6pHK3Zy8AJN70hb16OkvlJlxZZlAzI4oZcd24QUDe7Wxm/tu46+EW/ulWjjSF2L7CYjXe/nHh8lxq5Z1opLnDpINoBVgw8Q9R7hvshC0kHjstTQTieRR3x2wJocn6ZtDXbB6QoFoIHkNjjUPq/xNEAOJFsI=,iv:pnhe0pEepbst86Xr3ux5jqi8kIbFadIAk+aarCX0Ze8=,tag:hKJAg+B0U++EOF5CGhtBtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
