apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:XewBym5FqrG/n6yU5shLCgKUNzbyVu0f2C2U4WARnJgnnsb39AhKl82Sjls=,iv:rPj52x6Jt7y2OUsKFEbTG3NseCQGp+mUMqg573+uiPY=,tag:o5yk20vkWZwYnkF28ZMkEw==,type:str]
    join.key: ENC[AES256_GCM,data:NOxSxZtZbVIwpUHFFehUl1pUdzFntnsABe/BAeN2Q5YBduLSpJ/vEhXI2DF++wewjvyh7VwXXVRY6nXR72lNAxJewSqfT+PZfzsNDKEtK/xWLprZXNLv2Q==,iv:pPJeWdBOZ6xLZDnLOloAMv5ZEuph49IUiZNim2sTUCw=,tag:SfjAcDK6azoHlhs8Om9WFA==,type:str]
    master.key: ENC[AES256_GCM,data:02exSVIXlzmhN7NSHPt2trJHBj4gOZyuGl+NzJOsoSW5oQ8PnEkD+c94yCUM3dLSiZKySByfbqtCAPoQlZJjIpdtFCriImq7QMkjfSKhCogYtRW67p6i9w==,iv:wyL15NGX1OdJE4Wzqy5SaDV2XyxdZfsaCuPduhaCi2c=,tag:GF+Gylv9FFr0MppN9IinmA==,type:str]
    password: ENC[AES256_GCM,data:ZxOPlUJwaasLrNx+WIBET3iO1yMEWIXP1N+Uew==,iv:AFfFRvAkTrROwCMBU1xlRozA3Arl7nXNM+iDGBWKurU=,tag:/ONe2P7RVhJb/QWqh5Dobw==,type:str]
    system.yaml: ENC[AES256_GCM,data:ieQz0wK8tIvoyjo8FHwj5pwkvK15xaSVwORER/mcGbsbr0x9YMalKB/cC37c6962WyEblSQ4DhorXc5Gr5cdGQbK4kWK9cAqMxT0DzOPE4Y/LznBzEYIxlqR1zjq+wTglWr9ce3r/fT+4K1b+6IuYyPsoAbO5kw58KNcRoWOb7Lsc0fiHsroXjGkJh6/aEj8Vi468hHU3BR6ZEFiOXgwG2qPEaHaUf3dgf5tLk1hzNpE+uXgfRwEZmbZ8GrW8GlTT5C76nWqWa0CJT0POEprf6md9IUhmHyZ6+cVa6pKm40jYfbJFpd8KLrrB7ULmZdEasjF3mCb95mwSzkVyFSHvCiE7HQmHFO1bnSSs2Hc1mPyoOThQFLYEKZjamOLNca33Ms+crZUGGiyXU2YH1rUCtyrZ7EfcJM7IqMuFVDHgiqgE8KnBvmPAYJg1ZyEKHZ//0ToXlKxyZ0Lyhfr/dwNMzHHP/LiMFRoD6MJ1UhvMeNLY9q6678YmxH4LBhkgNGxan86KXf+f2hPl5RAV870VT30MQr4Ht0yEQTV8Hifvco7mVwl3KSRWSgS95xMvrxX500Mo0jX6mW96A7tnBkeKPX2iz5bPbi0FhFkSHJOLoLOTaDfuEvzojPGmphMxRAWi8b+Hw==,iv:xKraCVdVbo7AvdEsKYd86W5o1BFw8J+cgYZx4S0o/tY=,tag:CTwcrPQyvFJsEafyxf+xBQ==,type:str]
    user: ENC[AES256_GCM,data:0u06CbU3u9wwJAF5ihQkjg==,iv:62qV9shofuJT9dA56GZvfMfj38oTkhF6wdtivr5gRss=,tag:XgWl9gWri54VfMcfRQvTjA==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPamsyR29NR0g3K2hWY2hR
            ZTBmbW1MUFNWZXBBVFJhaXZPV05JQkFvQzFJClppVTlKZkRJME9veWhaYWFZdERs
            MWw2cHk3bTFEWm9LSUtiZlVWa2hBV0EKLS0tIEh2WEhpUUpoZjlPWGIxMGIyQXhJ
            cWVsUy9wMHZ3cFlJQW1zUFlPei92aFUKCEInoSOva/3QMgLo+GxLy+Ed2yP+kdFi
            yAM4D1UM+oYFHlKq0mbqP+3yIqb14yEHK1mFA3unI1y6BB+dksJo6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:32:28Z"
    mac: ENC[AES256_GCM,data:2WforLDUPUXoV0MopZDPOlXt4OhS0yxPvb61Fp+A5JrkB+yCYCW1YZmKyb3renNvwvKJ1bRljtlMiheAbfp1qd/h/g6o+g+FhsDeN7sKpA+vJ6237jsMvZtpgCV1O/h8qEOJKS7d9uS0Q43pLC0aRHPSWbg++5Mk/J779xeSWpg=,iv:N/GeDQytKWHSjnr0J477lWsfTqThTWoszCth71f0R14=,tag:rdh/PWEsFzTxsyXbl+iA6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
