apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:xo3lCn66vy1Nn0A1blvn+Ajo0mi5e2Pra4tNfjWzT1wLIMfKrgIf9fRcDNU=,iv:IhrmXRgACYgoZv5dR8dtkj31UK37HjAA8lrcXuXh1JE=,tag:5j/tcrwE2aJcBdoiaobTJw==,type:str]
    join.key: ENC[AES256_GCM,data:+OqSnTZ2/egFX2tJcbZiN1OtNXOstjMZb2pDJzlI8NnypB2RuIPR2vKrJu9ThQ/n4CbCmk2bF6sFHjnMbRXnW3zweIgCR932CgAoqPcw92Lve0R+muY7bQ==,iv:WDCYmQa91lRL2nsq9xT7Vt1coDTqnRkLlxQ5FnGTn1U=,tag:LDMkFTR/Xn4Dwb1VNqxuKA==,type:str]
    master.key: ENC[AES256_GCM,data:r66hwkeQx9yxtFzHhpaOFshOwqTudH4s1Np8+l4kKEgBTGTJOWrvclCvGV+L0Ay8ah6vj5AJ6IvAPJNxvVcQjie9QiMkLihsgSC/1xMaGMnnp4zOqftJHw==,iv:bODcpN7kAeLmgTqrexnwlZT4h2iYBD0gdi2X29ckF/E=,tag:WUYYPTabEN7GLRwJaWLupg==,type:str]
    password: ENC[AES256_GCM,data:8RnW49R1j3TN/63SkPGpjEbtRIgHQwFCDHmdNA==,iv:KYP3fa6dr9MtipejBFfjcWBcMwmVENU5vFsMmmdHDIw=,tag:XOlNlXjm8tJC5WQ4BQFwog==,type:str]
    system.yaml: ENC[AES256_GCM,data:Fsb892z7KS44HGhCp/Ec4jNUhB+j2aCk6lGOQi3PiG999L4UIEydhy9SjhXaqtiARQiw/gmCnXO/23K/MrC9hmfnZ76KxdxgoIt4VUoq3RTmtuMFWmmwub3b/fPCwU1a8NzpXBu0WXXgMOSDalDtx++bDPhm8ZsvJ/lMI6RpbWRq9N4CHP1Au0tsI+lLAya68iVEOtV3MjlFCCKRAhdgnQ9qelZ/XF1jbJwOCdDyKqYUAxrtp0p3tn6BUFm32pqcUKfJfUbH6Oj18+WM1shN8mL+lryspEM9SYqcJayRZVQcemZe+2yW8sL/BydkkwjMmhzPqfRhycE2PHkvv/Lc1eqtnuphCTgYwgxTniknZ0vyur4Mag/jjlNCdr033SQdzF9Lpg77O++XYBEOmIlISzIAyYegXdGMP/oRuZPZ4zCo5OFQIqyFS8A5HleCpwjoyiMBY7hGuPptu2XeLZhrnlHDy1B+zBjG7WQLA+dK/wMgLC0LWMFxK43P+ah5EmEUHVleBQyEIOx7O6gDa9RqJBzo4pxt8fiY5BnY2tvMTViPv/kgsVD+KoOpqpgdeOyXMXoER8//ly3aHalYuJXgpiAVUUDahqwS7NIEg16mq3sKmUWu1/3AwlIRuwX5bwmTGgUO9Q==,iv:uIYjODcuZypIq5JvTv8NEfhObexPfwNmN9PFkXFoFLA=,tag:DPz5v7b+R13ANbojhc0uAA==,type:str]
    user: ENC[AES256_GCM,data:EZu2ND+gAz80yz5mzHZaTw==,iv:t+iNOzGeutVOvxr+ffZRq80BdTdBZJmdgdIT8aHK8tk=,tag:8nRvdnuVI+4KDoIy/qHcPg==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcE81dmI1N2RrSFdVcmlC
            R2l2UkVGeUw1Q2ZWazZuc0w0cWl1c0pwN1dvCk1BR3ZkbmFXWVlHd3hDdER1TGdW
            ZUFBWXY1WHN0bW9BaDh4OVBjbWdGSTQKLS0tIHBVV2dsSFRxeGtpbEM3S0c2dWZT
            bGVFbmJyc2lzd01GbDJDckFHdGtnTGMK1s0LQTbbbS5B/5Z4nQQ7hX63h0GUiiTi
            YrYuAjRy4dSFrcRXrGt7Vugrivz6TnbMJDruHsN0za9cn8261J0CUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:32:32Z"
    mac: ENC[AES256_GCM,data:+dUOkR7AAHX0F3/vXkR8V6agG1iIqm7dQxzP9wK9u+k1P+nQyLOYW5TpVf1GTgI5PriAQRErZ3NcvVEzp0vLOVl0wkcDcrRvDavQStlQM4gFUzNE8QUC9IFc+P3lp4EuIuzLUSSG9BkfHNKJcse5PAam0EgYp8NYmggX2SvJRus=,iv:lUHNOsU4b3cDoWKvHRUyelQH573nf83GAArzJFH/cwI=,tag:9ZCaL/mvG9bfKercigDrSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
