apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:3ZEPeaYKv2HMJpGcJhN885TAwPFBuZ0GWe4XsB7ye+TiPv4KHAcxOyH52Ng=,iv:Zlcb+V8cXDf83WcYQSXJGC9HKNpDbLcVMKGWm0dTBnw=,tag:6DVBdsI94MGx1KnJJXytNQ==,type:str]
    join.key: ENC[AES256_GCM,data:uIR07oMqBPT7NSRDoDdJ8GjuFz1Ac7P9VvG9pMj52iD+sFYNuzv0z8yr3uo/vePQsCcmO9mZAai60ZKJfKDaFrSEUPweZvtm6wZnISl29bFaFlLaJyW+/A==,iv:p6pcGt9nk4L7ME3drPhUyfB5QcgHAcY/t+uOcRZ/WR4=,tag:hY8FSrGXg2B22lRdwOGBjA==,type:str]
    master.key: ENC[AES256_GCM,data:GKWxKUZ0hEr8a7dj+bBBV33PGJfS4rBO/E0wuhpfNFdcpzedtAzXmJmbHnEZ8vOwnhXyEO+aMMJ7o5LU1apamEyx/r+a1HkOM6OdLsBtRER9KFLn0N7+Dg==,iv:iThO2F6NsQ/U6fRzqrGHUzB7TOEU6FkM8yI7bWZP7/c=,tag:9x6D++ZDYhQ0y7DbO5wm3g==,type:str]
    system.yaml: ENC[AES256_GCM,data:rp50FCfYpblErYpg/TRkuSG+o16aJsEC4xCCK62ZKMqGanCRlWH4VULqdxrCugINepOGepszNeGgLnsyb1+kmYCUb/TJagT30D+watB/L/lszN1pdZX7DpETzjZsLlAtsM36m21gpF84rJ/ZEMvVz5eBcv7jQgMxbt9eSWVOlsIbRTwladFlVxu4QXrpfKf/DXn2q7B6AT7x4GOXQdb+o4RYzGahkdhrdvwQAc/GAx0+OikF6IkKPIxG/sPMOGAVe6nnxlLtZgiKs8fLJuq9Q12VaflL2LkKlwMWUZjBYMxWjj7MVyrldMtKR1+mtZNvm78RdhML9IEHH7h7JMDdd18KKS8W+TnSXNairIbJo3kgG8ceXJzrhTsfzttEnc2bhs06go+dnjL8njnWZixJEw8j/qcegJo+Xlhniv2535ZuDXJYN1IqhrUN5aqwKm7JSu9nC4kXGODgLn7cTVcK6NaS4OjaXgNbmRnNXPqYgYvNSxcDyoTGFxTDFpJB6Yzd/4UcGLovIcLh2uFg3PKM4wDBBITMdYUCj4ocJdAgRgWw/bdlF+kzVg==,iv:zMA9VRK6XtiwD240x6FNdHhEgUoMJKfmxK0nsdjkOCw=,tag:dk90Z/06gn7qf/y58KYjwA==,type:str]
kind: Secret
metadata:
    name: artifactory-jcr
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOVRwdnVxQ2ZFcXFPVyto
            MUtNQmhMbVNQc1FEWGRVdmhucldrYVE4TFZzCmV4L05ONVF1OWZOK3VIUDU1akJI
            bTRLWWxrTElPN0RaR3JKSEJrK2FHTzAKLS0tIFI4R1JSbDVWT3JKQlAxTWZLWHdR
            ZGcrNkFtNU9rbzlBeFdDNUxPZ0diaWsKF1r+vLUiqz2C8UQ8iv01U35DXc0J5x1W
            GrbWOMhVuLh6AFQXXMXegeeRI5RGGpO1MPjiHFObsnv2SMFUu7lD4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T01:34:16Z"
    mac: ENC[AES256_GCM,data:9IoQshdYpQPVeZDhOXr80cOWAAah4DGuvHEDfvNtS+dUSVBSOI2CMn+0reIK2Q2MSp3R7vpBbRF0ERh1+ADDkWKIii69okZgEhNzJUGBkUq84KjwHrryJkm8YNqikLLYokamdr6hArt7K2MbKwSGiuvhB07WAb/XmddJv8aXB5o=,iv:RxOkTzNcNJLFjkhXSWZLMK3nPb6BT4n4jtSC2/CWw0o=,tag:7fs4HA1p8TcINAPtMrK4Ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
