apiVersion: v1
data:
    bootstrap.creds: ENC[AES256_GCM,data:6YpfBfNkJL3+Nd86qNHRQH/0trhER0G3ghDnBLMkYb87BEXBGs8FOnXlfiY=,iv:WieXFTLY2yRn6YWgjS376qBAysSYxa10DUFHdcBOHX4=,tag:Qd8YpxOoKRQLiyQEWzdM+g==,type:str]
    join.key: ENC[AES256_GCM,data:n6dsYLajLVDCHw1JST5M82DoogAEyq9pH/Gfy5YpM0pjGf1GP8LwNC9yo8JSOYFSANzKWfWv99FseEsHCm2twQChhtOqMwCKmfhS18OqzbnI+yy2bnBCpQ==,iv:dEcEdoG9YzfeRD30ox7bRJT0Ryd/ZHNcSYM5KnK89qA=,tag:JVk54/sM3Gh+onIS4IDEgw==,type:str]
    master.key: ENC[AES256_GCM,data:z+FVFVHzhJlgR2eq6UHK6QUR+wZl96ZcWOyAZAvp3m3WnG9oQ6RhDRjWU+BGpj8gf6vhQe6gkPZ8YG5h1Qv6i4Zp+y3MwBom42TX2PPXW0t8zAd+DMoq/Q==,iv:uI51nHK/Q225CNqY8NrMDVuSpHhjU/iE0kTgM8iaZYI=,tag:gajqP7oTAkKZlsUdGAuRrg==,type:str]
    system.yaml: ENC[AES256_GCM,data:dUxIRaM77aJh6WBdhYq/2N6invbcJdh7XX8Bb9LYDlQ4ajp3qIvPrdQ49/o57AUsoX4+WKzdEyQKxhCXsWNWSuVpyKcZCWr2farLWfiqFUE5azDVeKQ70qqL/E3GZpPRtokZq1TIPHkPfPCdWB8tnbKITxlAJMWkkCR6bR5rUM1+AnRLWanC/G01rUVTWSeIYxl57+KZvM9qQjucU7DS2T0biY0HtdlEBTdj2z0y7GkG1aVIZg9MGOsbjQUi0T8arTThDGddOFUqN3DCNo1F9P+if5Bsdvxj0LGBe3HqkVTMqB/0ylnbT0RNiVzSeh2a4tivq/W8EJmpC4z/gI02bFemiK0Lefd2WEbJ/8RJP7QCfAnQiWdXp9OtQsa7FVl8Gnv4TPZB3oMI6gl24PGur5rAaYE+E06UD8kRdLT9zQvb3ioyxlSbKEVggkdAKgD5fGdKajThLwst23W/1qUq9KASSQh9ywYWYm1IPQUUsMaCjoHv+tQophZN3y2MjSq04+c+EfgDueu7dKtQU08R2fPFFWjIV48l3ZImUE+W1KuymnQ+0llDsA==,iv:7VLfs+UujzoyRTCpmvCNsVe+aeNBjx9GyTwDHDghGgM=,tag:spUn81bp8oy+E7SE2m8iPQ==,type:str]
kind: Secret
metadata:
    name: artifactory-oss
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NGpXdkluNmhJNXk0YjM4
            ME9JamxBVDAzUUFBdjdvWnVYTU9MVDc3eVcwCjg1b0toTzRDUjAyNkRqQVl6VklV
            N0ZWVGlGMGhScERtVEliSHJuZ2lCUjQKLS0tIE9xclRjNjZRN3NVV3NLU3JxbWU0
            VmorbVJmZm9zZGxGaVB0b3dPUnBMbHMKd41agcDd8sOi7mU/Gq9TjorL5Ri3iV07
            fgqOZyfjT5uXUIDQp4zRXbegz9aZSvIE8djwSjoET9qKpehnDt7OOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T17:00:59Z"
    mac: ENC[AES256_GCM,data:Hl4Sa8R9Eek2WP5O96whCtuS/aybqS0Dr3ElSPQjIxy2oZgDuSjtkKWQjksA2it7KtqBOzBK/uPnegvJQksbiGng3c4+pt6BnrtYSS0HAw7UjJTFbDbWh1LJ2zg9mk+Im5AjNC43tH+6avxnoRj6FxWudfj0tCo6QxNoikUWnzQ=,iv:uKshHELPAZ9iAt8gQI21P6QWoTTa2jiwNyXrj+6criE=,tag:73MJU3/UmBHePHu7JjpPEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
