apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:CkpeiBOrTeXThdhlUCdYVOBeekPi3iJTZWudbLT8nCxIVlzdkO9QSkOLMX9PpSGevMt+x9eliQxx0nH7JjqdFh+JqiSqztQxKwocyjKbdGc2hQi/VdlbUfxTcig4EN5FSS0vkoR5nWt78ayVrHSBwNeGD3F+OwUVcaC4ZNTRK65WjlRauQvweHrN0rgoL0ZoLtH59V1o/Qx21YhfaqlObJhKN8J23I9vc8U2fCLmM/H4TdLdS1yEhWFD8tBINEaLWNyIi7rwrssNzFYDujQ/VGmgRmmfIW15m0l7m05j9EKKPrfRxA3baZCjw4WMG2XygogWEwMrGOOXCebPxOMkhQ2KDjGknQH4fpo76RCOTPF80jAV85fMEFNRJnCaoFh3/zgME352mZe/8wZJMxRkuWwmk4b4ypHb4kKngKGH9KyV0m/YRREFcuC4TqWXexl7Ce01m1iF4GnUZakKJ6awlrH3OvurlF8KIz3xNO9Ww8OikW5S5+Fyo27IOSMLGrKuHwORZEcvN4gR5fwqBzMsLC5N93u7+4FPvZhbO9VQgHum/rs4LfFjCT+7uX91bwqid5caGZfThGcu1TkhjVYmLjbaL3AGMw9PI7nO02E9ef0zQIai8n9LJQbU1BJes6CIfocVZaGZa1gEnV/joycEzVuR39fdF0WGRHZ2XZMmtNX0DJIli3Z2evLgTakgVqoyz9MFHh4vRkBrwrJn53J/OaM8li0NKmezmR6gjK3ph9/Mz1C39+nNqMmJXmb2JlKvuX5up3qkuQKbUOkOJzyvgA==,iv:P3jZmv1gmb5ZnaPrOxj7aBgX4VOT3QdMxIw+fJhENXE=,tag:6ULGsjPva50Y4OWGEGEY2g==,type:str]
    config.json: ENC[AES256_GCM,data:9SVF/yxVsINsko5c4/QlxW1OUI0dfbrkiUrPmK9AEOl0e6MUvLMud+73gxntEsMrNGOu0oqbf5lvV/IXl7JKliXXuN39+/psiT2EO/QK/aIsgTnBd5vfVSudOxhcGi2Vp/yMFBZhmMsRN12dkv4jthMPESPvAhFi+VQVVJRUif+yt753lvmQoHwCx1MEeN0j3kiflMGxboegze35p2VMkanM41aM22Tuz/MHPksyecs9qJRhe2pP+xiJeM99TPVsfESjEDHgw1XRPkTSoArU/JX6xumjtKXof4wgNBjMrA/hV+SnAFKy9Dl/4O6zGtvRTOBkVHWW68JkOUeygWsssVaRYkwQiLbgbnzkJ9M1d5istsg+wpnx1mO2WAWm/icAhCvkIP+W2Mm64shzpBup5fHpR3O5xSFNoUNQU65bfbZ/D4rza16DuTdLO+PJDuEP5izkpl/xkFcIUK1S1Y6bwk1qAUl4sLXXvP0posbK5bRbuBvn2N4QPWDNDbb61OlB0Bk4FtA9vdxNWs8vIoDvlQcsyiOrGlyitN+wcX1wPtjegNcmoGqVyro0kXv8PZ5BW6uBtRZncJ6waqT7j70J0rCS4Shfyrom2QDAGvvncpzbLERDOS41F4UjeQEHJyDRPBN8dWppHK84+6J90EwfHjjeuNmj8qYvmCqAJrH/mmieovieFO4KQtl6J1k3vER2GzcKva+qCHIewn1kPMGVF6fVkUQLaSvQ3st9Gh2YMWYjH6hgixKJq3dFF2Qxty0594Vx0Q0zMmkOgpc0Mq5OzA==,iv:txWYdr3YhlvGF8vI2QRNHsN5+UpvafgplNYqK74eZVY=,tag:CJ7Mo2SRgyFHkvNKFr9bjA==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: infra
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTTd4UlhEUVFmUEJpSHZN
            Q2NOeTRYZWI1aUxrRUJyYU1RT2lZc3gyMjNvCmJqMXg3SWx5Y2kvZTFsaC9aMHM1
            TDlGNWtoOWdWSVpXdDhaUUN0c2tHTXMKLS0tIHBobVJIcUkybm1VUytzMml3aVFw
            MGlwU2h0NnhpS09NamxrM2lUVmNBV2cKKQG4BNoa90cS99ecY2hWOQoKIJNU9m8Z
            j3b4IZPcqp5zW8Zv8r3/lhTeXeEDxlLt4H8anHFI+Bu4gTPRJEDBeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T17:59:23Z"
    mac: ENC[AES256_GCM,data:sfLl0jz7ikv27ECbZuHjscRotL/7ILkn5+dyBxd49mU6Xd+Re72ODGjleARZrBgLVzaKvYmaZooF61PDQII69yOQg9sBPEd/kpCRWVQ8kcVgFyKNdM+VIie/lF7w1vaZ+h7GcbFtYZZZEKj0+xgf9YaEZ8VsZleq61NzrloOg+k=,iv:5napZXnaUzbHygUx68IU9B6+xM0PUtoqp7IenIsuSJg=,tag:AdtpTmqt1M99aqEvaxoRDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
