apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:LMc1q2BSHfiWoq7zBKXMJvBiI3qQGBJ/2ZS8p2jVO6kGlLNq8+vRczQs2zp19pnzDGraBHji1TzlNBFmsBpZwO0fBdrTyqmeS0BiRvhLmUpr2ZiQBj8rWfdXtgPIxPj9GzFE4VyzKJlxcBHt0PxaTkLbjmImgEFCA1LSz8JGtEAuGfdTPvgvrDcNM4LD4EmdaA/uRQk8ZqJaER8AVy1//f1WzdatRLo1c3/TQhnk9ZOzpVxZSwNN7ZwLxJxjuYY3ez/vRh5J7Gpzw1SQe4QzfMRlIobNt7RlVPmBdEbQIoDPgkfeFfMV07TJDkISB8JM6a8XrZn0k5EA9NxRZ9ZwPzF70n8sHPh3SQwkgJWgNHZuhiZh64cBx2EouAW2EKNWoF2KIfJkPomt2Ykw2sYVzEnBNfbR38ti6VJb5Ac0cxqhAEEW1VGlitlbmkotrQ2seUJJHcDwcUMHvtuTxUNQkamYQZIvicufEc5nv9gsoajKPM9d6P56d1crGlkHwyk0jye8Lh9ku9ybIBnWdoLt2ofHetfjMLn1bdlQb8+EMIG/vQJtRZuASIWhII3a1e3ji9kAVJ0bB2M94x8CMP+IPGB+t8uKzZIqBG7dXoTSHC33XO5LlE7ou5ykHwCk0bZP2o3puW1b0Fjgw5tBCjSJ6jmkgVIk1IkjhqtYEwhkI99aswhF7QRb5BFPiJ27tWvVd3LvgqOZ8Ylu7mmYP3vs8oqzXZi/5koaiGz5HooGVfOWVhbuoUieBY5N40aRhAhOgZuphsAWdCk=,iv:a648mHz1sJjzBgBKlONHCC3Exe2jxQtAE27v/z0ENbw=,tag:bpuftzlCpScGQOqKmGLT3w==,type:str]
    config.json: ENC[AES256_GCM,data:thpCc1x9LF6FPHCJpB+sMr1cLd1MMyUkLV072/+T4nabYq5c83FLRIMnVJH7RVuIzBzCFSZQEsWi7yQT5idKX3N2OxpXu/wn6SvQAgTZZ0/oY2c0ZVWoIka2bbRNfK3zvGqCVomQHwSvA3uMj7mKG66YGO1+zNAvP5Fxh2zIC3grbxMCW1MCtTItvgTBnl811C7i6zujunVnt2LXVbddP47UGOIJs9SKB3l52NLE8bXL3eszxBT2DoWge6Pbj/p1uowSKf+LUjpToVXE/onGFux1FS8ZdbhgIN7+7ElF9kq70B3bzZwL1xo7z3JRVUDGBMhYLmuxtyHbKMH1xjwu/vcrkwRrWK8YW9+j6Q9ehjKQUkBIs2NNC/vhhKF/Qvb1KkdfJYSwPPoEMCqrh6nZQMXFHQW2/2DjVLCo9YZ316mnKbjnDsBWB3SNsmEx0zP8kbvsRYeJ2Jx2spCYITrv8F2oXq+uHYELHC9WFRB5+jy86je3TYZLm0tN02+pxnoVWggMAgUTc3N7fmAx89N4vnjh1aDHnwW7fTJ22RG0+4j0hP00oLEV5b8V6pE+UEJrEAzRqISdP9Z9sFuZra/VWmwJRT2MsXtaBwSkUj8NOww0JmhjFbf3SUdFgxZj5qSqEEOdAAmOpPQ940NGI6Hnwd8DzivzhZpuiRP560HLXWIo/mHF6zFy+KKcAraKl60L1on1uUwf8Fi4p0bayPju2EryDD7tdtBNBJvIxiub2cjvbkGK7Xa9N3RC0C5qhgBk5aWYOIzKBnw=,iv:iu3ggBk72gdS11wCiWCxu/UZ7A0s+YXmGTBRk3W7W20=,tag:Rq+gHne/fTDKIAsrGPuw2A==,type:str]
kind: Secret
metadata:
    name: docker-config
    namespace: int
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMODVZY3UxY2xKT25yMnlB
            bFd2TTNOaTZUTkFJeVNwYkcydEVrUkJhVlVJCnhIcUErZ1Y2TmxDSFRFcGJ4NjVJ
            QjFtSzlaUGdDSm1TckcyRm1GZitpM1kKLS0tIEw1WXB5aXhXaHorTU9qalQxS2s0
            OGI3cDRxbW1uSTZOZ3U2OVlGM1M1Vk0KEWDEGHanpEiQCEjWLke0yOYSwSAN+BqE
            KTYhik9xWzg3PnR284cS2RYmPtwuKcZxHxMP1iBJzB7ENwbPcoLZew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbFZhVWUwd0dXWTZoQWcr
            YzhLYk9Kam9sR0NKYVBBZlpJeGt3a05MTzJZCndVSEFkRlFFY2VIV3pRenVQMkg4
            aldOY0IybGVHV2VxZGV1d2c0WVlBL3cKLS0tIFIyaEdKZDVkWDYwd204T0tySDZV
            RGcrRWlwdlZudlRCb0RtNGVuUTl4YkEKeuuWx9FX5o2uJdjs73FXDA8klJtTUpzT
            UyyyR9w72BMsKaHglMdM3VeBupEQS7S8okaClX2MzrMpEVEtRml+qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:11Z"
    mac: ENC[AES256_GCM,data:UOfRxFtrKXlK+m2DJPjlxxoyzq03b9dULYiXD4BkL+PFsBbEWwzrve2RU4AOp1Xx3ousTRGdMSaULGlIiC9be4NIrJ0Y+AxKedzEb71GSJ8K1NTs3L5B61sfOYUNkdRfYEpMC/EOld0PCGZgzBn+MNZZhgQG8urJ/vMJ4Tbtyfk=,iv:6Tl0aBstG+i1d/+7wArb4RKM9Sae5Sgo4uOuO08h488=,tag:suoqzaifAjehwat0psou4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
