apiVersion: v1
data:
    console-password: ENC[AES256_GCM,data:B75GxB//xnjMsEqSG0BXRg==,iv:TgtjVDcpmW57hGgugG8Qo3o2OjUuURSsj4hpxD4x9ds=,tag:40H0vB+R+jzGu+lIjuL+2Q==,type:str]
    console-user: ENC[AES256_GCM,data:JBzs8Pe78sB6ZtrNQ8hU5Q==,iv:E1cbuoF2m+XVfomGqBSk59h9T/sr2r0wyIUjXOUHNLQ=,tag:CwNn7+ozZ+vzT3BwbMeTMQ==,type:str]
    db-password: ENC[AES256_GCM,data:BAAzwlYzTRik46ohR9kcK4uIq+fB+mub,iv:wqv4m7fs3r8SIKpNmzN6g5u+zeCR/vDWbGYceG0qi4o=,tag:+FXhKbF7FkA0YlmYoMFU1Q==,type:str]
    db-url: ENC[AES256_GCM,data:0g6zKWsLvTEkgi0/g5WHj6cZUSmFLrWXpaS3pAxmr/HkTD8GSl6RxPpXmXp/1Ao5yTgocReKQhNDKh2Rh55PdA==,iv:R5usgurM77gxV2LVw8C3Cv9TBNl4vr+1WfbNEnI7Ovw=,tag:v/9R+ugQRCt9ABTuYTn5kg==,type:str]
    db-user: ENC[AES256_GCM,data:5saqrZZWoHhfHSCk,iv:VLLM9nKshav6j35jWrtKqbpvKeAih3uXOLKRdRzjAY8=,tag:yVkToKr/xUfEGq98EXmIHw==,type:str]
kind: Secret
metadata:
    name: keycloak
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bUJVNW9uTmRMZkRmbS93
            RjVLbGdUSk1jSEtZRUkrM0V4N01TVDJYdDNBCmV6VjV5anI5b0ZQbi90WktaK29x
            Slc2WVJpOWlvL1U5SkcrZEpvQm8xcVEKLS0tIHFzWGc0RmhsbWtQTkR6QkxzWVV3
            VVZ4aThndjh5WEFaelhkSXJPd2Zqc1EKuXx4hLl9hsNz5+c231JZhIAt9pgPL1Xr
            IqXB9p8dGhjorJYkzEDZ0Ibkj9Fgk9SPPTFmUNaoN7OK1Iiw+DIv2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T02:34:51Z"
    mac: ENC[AES256_GCM,data:JWzzWc6Nxuf42ForUslMj0VZWuGvja/1gEzle1z3TT1zZc32VXzC1OeOnh0P6ON2OzqHPikzY6dDf9C67+I+qBmAW70kGUtvZLAhGUcbCIWbLNK/Ag0jhRdDq2senEpCvJvysREocHakKHKuE4JPeU6HhlNzmpJQ0p5Fe8beAnc=,iv:hz67CgZbJ9z4zQjNjXcF20rRpHhAVAr6JwIHicb28l4=,tag:IHNwa5vMT3qTpcT91QC1xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
