apiVersion: v1
data:
    console-password: ENC[AES256_GCM,data:CgBj3vGHVjC59E8ljYyZLA==,iv:TId9gvahpMjAG1O49VQIQafK+VPlFcpYpPo6Fv28VNY=,tag:rsWsSD7QzeTxhT1VqGrIWg==,type:str]
    console-user: ENC[AES256_GCM,data:ZwIXk4CzFisHRSUr8xOFSQ==,iv:8Ld+zmVtx8V0VsZSYx2puZMbK8cfipEIxgSTqc1UlTM=,tag:gX+JSMN9UwR65LfKC5Ssmg==,type:str]
    db-password: ENC[AES256_GCM,data:k3PY0g1S/GAdW9XrB7CNGoquBKOdDQmR,iv:hGFmcX7GhEqxRh8FlGa8OSDlLcNA5zTuXpJjWWshAjA=,tag:mKmLpP5/c6t1sIITiNsvsA==,type:str]
    db-url: ENC[AES256_GCM,data:z7B1GzWUaUTogPrdjfGOmJF+fP4lrWz2apDBrKgXSHG7LxT9LsS8TJYxhKl+gySJKaAvdfI8Q3E=,iv:mSr+2D8ysyzb+0Bc0thMxzdXqKXmiYW9MoX0JbafICc=,tag:yenWMQ4VJZo01cYFYfrE7w==,type:str]
    db-user: ENC[AES256_GCM,data:YM9e53MoMLaHpLDe,iv:7dzUJYnYaY1YkbdI+QpXYXkWwY6Ub3IEBUw68hMd6/0=,tag:l+V5Wq9ePubqEOZsuVMhTA==,type:str]
kind: Secret
metadata:
    name: keycloak
    namespace: int
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWTZRKzB0T1VJaUlyaGZT
            cmY0T0hYanpSbzJkeDJkY0NtUXl5TVlpY1dJCnBELzM0RGJpb3NSeXp6WGVnUkMv
            NkxrQm9RNFR2YkVsZEM2cGlNZEVWcW8KLS0tIGNBYTJMQm50NFB0bVFtRFJMYXBZ
            Y3RHSDMwT25NRk1tL3IyUjdiU2tYNGsK42coK6eMWl4s2TipzcgaOOujeX5QiHQw
            tdus4RabkQHiMLHaieV29/Hv8RI4TACFh7P1vU+r0sTtauFLr2JZiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OUhENXlIQkVSd1ZOakVU
            YS84Tng1c3RYSWw1Yy8zZWgwTWwzYXlLcWtVCkVvUG9OVnVzbHphS1FZU2NWREk2
            NU1ZY05PU3F0NVFzbHZERmdaVG5vR0EKLS0tIEZIdC9sRGdiTisyMzJCemZJOEE5
            R240RlIxaG02cjJDc2FuNk9jcVdRbUUK8wDSPtiDxdOrTI6SCAogprJ+vyU+n2RE
            1s0VJUxi1heFu7KiJ4ofR331UpPQU7crTNf1s69f+zZRL7MsIHgB1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:11Z"
    mac: ENC[AES256_GCM,data:+sANRbhwUKokmubxnKYkssj/V1ncvtVVeI9twvO3KDVILMys8cgOUHbsmFLsT6IXPQ0vp7brEpePIFok8dK+MATTx5LgsyslMaXkOa4qVdg+OSKYQB5JdxksBoidGVuWXdw/5P0Ec1YUVK3b55AlJnMoYjtaJZShXWKOxUiALbQ=,iv:XAhdLjN8k7VLAK74B+Bv8HrZ8Hzz8+FicgFaHoIEcgw=,tag:vfq3qwpDfPIKPLMFADA8+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
