apiVersion: v1
data:
    console-password: ENC[AES256_GCM,data:NcZDcE9SY2cKKujBRCn3Gw==,iv:wPHZK5TgIPwP2pU60ogG+Nfsft8DQhHXEBQa678Grns=,tag:0KEGFiVuCkAGj+95D1dkBg==,type:str]
    console-user: ENC[AES256_GCM,data:LAwVoMKilnjxZOQ/71m9YA==,iv:klZFOlif7iB3yE8kpcVMqDgcXsmxGZkb/XY89VfJ6pQ=,tag:o9RHL0LIJHo8ltLfjJe1iQ==,type:str]
    db-password: ENC[AES256_GCM,data:T9nCWL462Ok87AOWwFaAoE8CvBc2T8m3,iv:9vMclQecsYQLhIiuPXulh8G8eXwxg+1K99L6VuCdPdQ=,tag:etD/w2ldQ0S0exuIuL3lBg==,type:str]
    db-url: ENC[AES256_GCM,data:39+X6mzrTEaA5HGI4Av4MotwZAKEzNskpTyghOpgg1NNG2dmyQ7ngkj2rlPntM+nvsxc0xFYcdk=,iv:7qaoRSB+hY1QNZSnr0f7coDQa7bP9nLq0Pv6tv49Vfg=,tag:/06qz/nr5BHCUBgHAafzlg==,type:str]
    db-user: ENC[AES256_GCM,data:d4Yt3s1bVko6abwi,iv:1ZOg6UwKIg/kwe6sRLT4dHp+QaBSkGqCzyDZDaoS5p4=,tag:j+5vgRCEeCIZra2WQPBlgA==,type:str]
kind: Secret
metadata:
    name: keycloak
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNENCR1E4MXVlYzZLcmJQ
            dFJwY005ZUh3WTJIVjkrOUpiUnlHQXMrQlMwCnBuWE4rRnNGZjhwTXJubWx1Qmsy
            YWNVZFhhZ28xT0t0emxUTEpHeWZ4YlUKLS0tIEIycW9CZUdKUXlxUDNYQmhnZGN3
            VjRVaUhJVWZpTWZlK1FCcStvR3B5dWsKd9ZhwORfhkqvLXK2loMOiKoVzeTVLJ1E
            XSuELWbu7f+LEi/X4axzbiWIGKEAxl49vtgAF992ZkiMPGWZ9zpQ4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T11:34:12Z"
    mac: ENC[AES256_GCM,data:XIWBm8dDBf3MOqt5uFzTweskzSmyBLVNog7Jiv0LWauWS4YxJ1XMhzxQOWNt/cU30JheVpiZHoIPj4ROKdzZl0mw9yaVx0bEpDabf3sNVmk47aAivuS6TeyxHnnTVLXuQOQVDK1Ech7rM5emo6wLWbjpLhMZgJTnMO1FmXai3Ds=,iv:s6d7W5IAWZwfRQIboHxZAu0T9y2y354WVPlVrLsN6zo=,tag:OBUNGswYVSSjpJODRCpFSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
