apiVersion: v1
data:
    db: ENC[AES256_GCM,data:aDAcwK2OyHnZduNK,iv:hH7BZPIcc8oTuZoSG1Xe79NozVJPNXN4LXAvMOYEnGw=,tag:H5xuKGKTeopbWaD0usBFAQ==,type:str]
    extra-dbs: ENC[AES256_GCM,data:iBRFEE8xARQ1t4OzDBYBHK80m3l+uW9TL0ddWv0ebJhw6l2X8Rupqd2KYvrANmoohX2GW/GgCtyQDd5Cq2uERvaJKApoRYOc/qXUjw==,iv:tDyVCbpnS0bh0c2TndGpSkjgjGDbe7phZYGpJAAh9Jo=,tag:jALqi12jW5kbzqR1s6QLOg==,type:str]
    password: ENC[AES256_GCM,data:POXrXb7FKxbTz6QK3baUhRbwpI7jKV8e,iv:Ye/wYkgvWsFA5u1zmuBLYB3pe3sWQOyriU4IR+E5jno=,tag:QjfqyZmN9xzjTNNmUhFLcg==,type:str]
    user: ENC[AES256_GCM,data:iaNk2j/0wUW+ZRob,iv:JQiYYIkPvSKvfrRj21Ew73HqeMmSyxQHPj8RPR06Pqc=,tag:m3scpzryM7DjL2mOJsSf+Q==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: infra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RFFvUnFSdGJkSWJMR2ZW
            M1dZRUZDYUdEckl2M0VDVC83blBBYnJ6eENvCnp4cE1hc0ZzTThzMVdnR0p6T01B
            em91bTlDdFNHYy9vSGliL0hjaWdkcHcKLS0tIFVuRDZabk5kem1DdzhzaVFHcnRZ
            cWlIYnRxS2JxOENyQnRXUzIzUHlLVWMKtDh5uypH++r9p4zbO49eQp3zKa6IJQab
            RZEf2ZDpuOhaT0EV0VaeunQfLH5cHU1KoLBrq5beOJIFZhkjjJhEOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T01:59:46Z"
    mac: ENC[AES256_GCM,data:FVpp47xEokhO72WfhClcUSIIY459zffkLSPEOiWPQpJR/X2q9L+Wy3WIKf6OvZ5dcWY05J4G5vEi0np4EfU2Z7EWbUazNLfTf/XFm7oort+9m3NglTZsaTv0VPdhLkoq1CchPk110w85rVhlj8xl9QAvlkfTuFl/peRvjxt+f+Q=,iv:P+8jx62rPbjxL4t3mrCL15lFGySUKUiu2y4JgJsB09g=,tag:2O0VuseXM20iIgWr/T9HDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
