apiVersion: v1
data:
    db: ENC[AES256_GCM,data:JfbZv+Y6dsYX9U7I,iv:si0xWNgbKXijcchUgHEgv3YBBcLGK1WyG0lOWsIrebc=,tag:EJ3jIA6UEl3UYZ7GxUk52Q==,type:str]
    extra-dbs: ENC[AES256_GCM,data:OE6/uvYUWVdgGb9//ZArIvMJkSNCtKqC1RPMo1A4R3N31BIcC2l63RFOgzL1MjzUS54pzuKLhhPcxOVNrS44OprE520Q0H1N4VaKvw==,iv:4yavuk//tjLV9ADVJebKiiiMNlzS/rVueIVOJSvHyXk=,tag:SihsBa9ht4X8yrmXhAfI8Q==,type:str]
    password: ENC[AES256_GCM,data:TOQuME2prGQNw9873l/V/liiLPCFDcug,iv:Rw3OmXKxjretymEa6rEk66qBz/0V4nk/LS7alMt1udQ=,tag:MhwTHKfqy5H8aa+LXcWJrw==,type:str]
    user: ENC[AES256_GCM,data:KkqTPIM56OPwat8y,iv:rk7hlPy2U771DyuEaZ7qhU8IkNqpwmJNnk1ONBhtW4I=,tag:aj2zcVMGiCkf8hfOyYemGw==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: int
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqtfy7qnvac57dm6dp3k6w3cf2m367gx502d6nl8fykv847u0gnssgkcpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UlI5a2k3bXl1VXpZaUx6
            NEVkeHNTeHpTdUFvVFkwejNpWEZHNFU3QkVBClZGcy8zVFp5YzBFMEtmS3BjRERH
            Uit3dnd0Qk42Q1RUVVRsSi9sRzB6TU0KLS0tIDJLZVZUelZYNlc3M1dKZW45cXNO
            VkwweDF1bEEvS1FLY0pYV0k2UHlaTmsKqUdhLbohpaHcg1JEf/+GMgqRRXk8qrBY
            ZA3QbUwZdjYgl0Qxc0hzXI22UASFil5jEYMFotujBoXJyq0nTbY2Rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0tpa9akvns84dy28jaujch4z3qrzltr6x9s7l5frdussrdnqqszcv9hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVmhRV2VLbHZHckVvWmp1
            TTlwM2NyTkdEOGlYYnpLb2ZzbHMvWldaaWh3CjlWRkNBYTVuYmx2N2FEWHd4Yi9I
            TjA0S1FuQnN1b0FqdnRrbVcvMkx4NzgKLS0tIEZlNTFRb0pFL0RWUC83b0ptS3pz
            QUFSV0YzdVNVQUZWU09hbXNzQ1gyU28KkLBefXRCcEYqft8n4NV63dchBd4Js39z
            D0SEVLzafF2Gbo8vCohvsW/lU1Dw97aXhehTwi25OB19/zOC+m9llg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T06:13:11Z"
    mac: ENC[AES256_GCM,data:H0imZLCEQ6s45+wEnnVoJUPJ1dwIOtwn2WmSlqEdRODDGHI4cKCxBxSRCBGw8tIcN5nByF8Rj0AA/VVDTRqO/M4vGJpaw+wUQ0x99j/ZPWxlTjXuemmZvXC41T0S8Ge31t/JkmaWPcACI0xi60XPbrPdJNbLlz8PXteWrvA+U08=,iv:VlhelFeF3+MlkYcriGtOFKP3DadOcNF5FTpEip2+O/Y=,tag:cJMn1/ETwvnK17ZMFMGflQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
